### ISSUE TITLE
Parsing internal wiki link to footnote generates incorrect URL

### ISSUE THREAD

**Issue by dregad** [dokuwiki/dokuwiki#1968]
Direct link to footnote 

  * works OK when using the full URL
  * with wiki internal link `[[#fn__1]]` the double underscore `__` is replaced by a single one in the generated link so it does not match the actual anchor

Example: https://www.dokuwiki.org/sandbox:footnote_link

**Comment by dregad** [comment]
This problem still exists today. Here is the root cause analysis.

The link is processed here in \Doku_Handler::internallink()
https://github.com/dokuwiki/dokuwiki/blob/95078f236f25cbd6aa6d3e5aae7a3f3d39de6834/inc/parser/handler.php#L880-L885

resulting in the following stack trace

```
pageutils.php:126, cleanID()
pageutils.php:251, sectionID()
renderer.php:877, Doku_Renderer->_headerToLink()
xhtml.php:851, Doku_Renderer_xhtml->locallink()
parserutils.php:691, p_render()
[...]
```

and of course cleanID removes repeated separator characters `_`, causing the problem
https://github.com/dokuwiki/dokuwiki/blob/95078f236f25cbd6aa6d3e5aae7a3f3d39de6834/inc/pageutils.php#L160

I'm not sure what the proper fix should be. Since we know that it's an internal link, do we actually need to call _headerToLink() ? After all the input is NOT a header so would it be OK to just get rid of line 851 ? Or am I missing something ?

https://github.com/dokuwiki/dokuwiki/blob/95078f236f25cbd6aa6d3e5aae7a3f3d39de6834/inc/parser/xhtml.php#L847-L852

**Comment by dregad** [comment]
Still not fixed in Kaos. If someone who knows better can answer my question, I will gladly submit a PR.

> I'm not sure what the proper fix should be. Since we know that it's an internal link, do we actually need to call _headerToLink() ? After all the input is NOT a header so would it be OK to just get rid of line 851 ? Or am I missing something ?

**Comment by michitux** [comment]
The intended purpose of this kind of link syntax is to link to a heading in the page. The code applies the same transformation as for heading IDs such that the user can simply supply the text of the heading and the code ensures that the link points to the heading.

Other IDs in DokuWiki are intentionally not following the pattern for heading IDs to ensure that they won't conflict with the ID of any heading.

I don't know which IDs would be worth supporting in addition to headings. If footnotes are the only ones, the code could check if the supplied text matches the pattern of a footnote ID and use it directly. I think the double underscore pattern is quite frequent in IDs outside of headings so checking for that could also be an option but this could more easily break a link that should actually point to heading.

**Comment by dregad** [comment]
Many thanks for the feedback. 

I never realized until you mentioned it that it was possible to make links like `[[#this is my header]]` to have it jump to the `=== This is my Header ===` section... Nice ! For all these years I have been previewing the page, copy/pasting the link from the TOC and inserting the anchor it where I needed it 😕 

This feature is probably more important and widely used than my need to reference an existing footnote, and it probably should not be touched.

So if I understand correctly, achieving what I need may require introduction of a new type of links, e.g. `footnotelink` in the parser (Doku_Handler::internallink()), detecting the `/fn__\d+/` pattern, is that correct ? Would that make sense, and is it something that you would consider ?

Alternatively, what about introducing a specific syntax to reference a footnote, like `((nn))` where *nn* is an existing footnote's number ?

```
Some text ((this is my footnote)
More text ((1))
```

Which could render like this
```
Some text ¹
More text ¹
___
¹ this is my footnote
```

Let me know what you think.

**Comment by dregad** [comment]
Note: I am aware that I can do

```
Some text ((this is my footnote)
More text ((this is my footnote))
```

And it will generate a single footnote with 2 references
```
Some text ¹
More text ²
___
¹ ² this is my footnote
```

What I'm trying to avoid is duplication of the footnote's contents.

**Comment by fiwswe** [comment]
Whenever you insert or remove a footnote the numbering will be adjusted for all following footnotes. Thus permalinks that contain the number of the footnote are not really very useful (unless they are used and maintained automatically).

What you would need is some (user provided) unique id in the footnote syntax. For example something like this (the exact syntax probably needs work):
`((##<myid>## <footnote content>))` I'll call this the _defining footnote_.
The default id would continue to use the `fn__nnn` naming system. The manual id would override this for a particular footnote. So the old `((<footnote content>))` syntax would continue to work.
Then you might use that ID in two ways:
* `((#<myid>))` Special case only works if the `))` immediately follows the id. Equivalent to repeating the same footnote content from the original footnote. I'll call this the _dependent footnote_.
* `[[#<myid>]]` or possibly `[[#fn__<myid>]]` A direct link to the footnote which assumes that its id attribute is set with this value (and that this value is unique on the page).

Issues:
* Problems might arise when later editing a page. For example then deleting the original defining footnote, what should happen to the dependent footnotes?
  * Similarily when copying sections of one page to another, the original defining footnote might be missed.
* Guaranteeing the uniqenes of the ids is problematic.
  * Conflicts with anchors automatically generated from headers need to be avoided as well.
* What should happen when the defining footnote is placed after a dependent footnote on the page?

**Comment by dregad** [comment]
OK I understand.

Tanks to all for taking the time to reply, and @andi for the pointer to the refnotes plugin, I'll check it out.

**Comment by fiwswe** [comment]
@dregad I took a brief look at the [RefNotes Plugin](https://www.dokuwiki.org/plugin:refnotes) documentation. While it does not seem to solve all of the potential issues it does allow for named footnotes that don't need to be repeated (see [Multiple references](https://www.dokuwiki.org/plugin:refnotes:syntax#multiple_references) and [Named notes](https://www.dokuwiki.org/plugin:refnotes:syntax#named_notes)). So they may solve your basic problem. I have been annoyed by having to repeat footnotes as well, but I could not come up with a good solution.
