### ISSUE TITLE
RSS Feed "subtitle should not be blank"

### ISSUE THREAD

**Issue by KristjanESPERANTO** [dokuwiki/dokuwiki#2239]
Hi,

when I verify the rss feed on http://validator.w3.org/feed/ I get "subtitle should not be blank". But I can't find the place where I could set the subtitle.

Here you can see the result:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.vegan-in-halle.de%2Fwiki%2Ffeed.php

In the forum someone mentioned the same problem, but till now without response:
https://forum.dokuwiki.org/thread/14144

He wrote this what seems interesting for this issue:
"In the feedcreator class I see
       $feed.= "    <subtitle>".$this->getDescription()."</subtitle>\n";

But I'm not sure of the context and I haven't dove in to figure out what configuration parameter getDescription() reads from."

Thank you!

**Comment by phy25** [comment]
Hi. Firstly this warning is only a "recommendation", not an error. Secondly, this field is the "description of the feed", and actually this text is not that important, and it is hard to give a good default to this (as DokuWiki didn't have such an config item).

Of course if you want to define this, just add the following line in feed.php after line 55 (didn't try this by myself, but it should work):

```php
$rss->description = 'My description';
```

If you have any suggestion about this, please comment.

**Comment by KristjanESPERANTO** [comment]
Thank you! This "workaround" works :-)

The "tagline" field (defined in the config page) could be a source for that. But the tagline probably isn't a good "description of the feed" for all cases. Better would be a own field in the rss section of the config page. But I'm not sure if that is important enough only to fulfill a "recommendation".

**Comment by phy25** [comment]
Opps, I didn't remember the `tagline` field. Filling the `<subtitle>` with that is good enough. That worth a PR 😄
