### ISSUE TITLE
Token Authentication

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#2431]
I think it would be a nice feature if users could set up an access token (automatically generated) in their profile. This token could be used to authenticate without asking the auth backend.

This would be useful for several things:

* authenticate API requests (especially useful where the auth backend depends on SSO stuff or uses redirects or where a client without cookie support is used)
* authenticate feed requests
* other semi automatic requests by 3rd party apps

Users could easily reset the token in their profile to deauthenticate all 3rd party access.

Note: I don't want to develop this into a full blown oauth authentication with scopes and a complicated setup. A simple auth token header should be enough. 

The mechanism would be simple. When a token header is present and the token is valid the user associated with the token is automatically logged in circumventing all backend authentication (getUserData()) would be called though (ensuring current user data is used and only users that still exist can login)

I'm not sure about how to best store the token. Ideally login would be by token only, but we may need the username for more efficient storage access. We need to access a token by username and we need to access a user by token. Suggestions welcome.

**Comment by ibschreiber** [comment]
Very interesting (an a very good one😄 ) idea. 
For security reasons I wouldn‘t store the Token as plain Text in the database, but as a salted hash. 
I‘d suggest to generate one token per App per user. Allowed apps would then be shown as a named entry in a list in the users settings without showing the token itself. The token is only shown once when it is created.
Also, if one token is compromised, not all apps would have to be changed by the user.
I think it would need just a few lines of code to implement this.
Kind regards,
Michael

**Comment by liuxiaopiao** [comment]
Is there any updates on this? Our team is also looking for the solution for SSO with Dokuwiki.

**Comment by phy25** [comment]
To be clear this is not a human SSO solution (you can already implement SSO with auth plugins). This is more of an app password / bot account solution.

**Comment by glensc** [comment]
https://github.com/dokuwiki/dokuwiki/pull/2432 looks complete. what's missing?
