### ISSUE TITLE
Link to old revisions on 'onceexisted' stub is not for current page

### ISSUE THREAD

**Issue by dregad** [dokuwiki/dokuwiki#3013]
When accessing a deleted page, DokuWiki displays the `onceexisted.txt` stub, which contains a link that according to the printed text should show that page's old revisions, but actually does not - the main wiki start page's history is printed instead.

Observed behavior, accessing (deleted) page `playground:test` on my dev box :
- onceexisted.txt link: http://localhost/dokuwiki/doku.php?id=start&do=revisions
- PageMenu's old revisions link: http://localhost/dokuwiki/doku.php?id=playground:test&do=revisions

Tested on latest master (13831edddf6edc68c9b5fe3143c3a22253bb7bec).

**Comment by phy25** [comment]
This `?do=revisions` link style does not work if url rewrite is not enabled:

https://github.com/splitbrain/dokuwiki/blob/13831edddf6edc68c9b5fe3143c3a22253bb7bec/inc/lang/en/onceexisted.txt#L3

**Comment by phy25** [comment]
Do you happen to test this on `start` before you test it on `playground:test` (i.e. you removed `start` and visit the page to see `onceexisted` on start)?

There is a cache regardless of `$ID` when showing onceexisted, which needs to be fixed:
https://github.com/splitbrain/dokuwiki/blob/13831edddf6edc68c9b5fe3143c3a22253bb7bec/inc/parserutils.php#L94

**Comment by dregad** [comment]
Thanks for the prompt feedback.

You are right, I tested again after restarting the browser and it worked as expected, so it would indeed appear to be a caching issue.

**Comment by phy25** [comment]
@dregad I just want to mention that this is a cache on the DokuWiki server-end to speed up syntax rendering, and this shouldn't be the browser cache :-).

**Comment by dregad** [comment]
Actually I meant laptop, not browser - I had to reboot after applying some patches. But thanks for clarifying.

**Comment by phy25** [comment]
So there are two approach for this:

1. Remove the link in `onceexisted.txt` and instead direct users to click on the pagetool button, or;
2. Do not use cache for `onceexisted` output.

Personally I would prefer # 1.

**Comment by Klap-in** [comment]
I prefer # 2, that would need removing the cache, or making the cache key more specific.
