### ISSUE TITLE
strftime is deprecated

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#3573]
In PHP 8.1 strftime() is deprecated, it will be removed in 9.

https://php.watch/versions/8.1/strftime-gmstrftime-deprecated recommends using a `IntlDateFormatter` for locale aware date formatting. However that does not accept strftime compatible placeholders. Instead [ICU Patterns](https://unicode-org.github.io/icu/userguide/format_parse/datetime/#datetime-format-syntax) are used. The Formatter also requires the intl extension.

We need to decide how to handle this.

* should we switch our dateformat config to ICU patterns?
* should we continue to use strftime patterns and internally convert them to ICU patterns?
  * how do we deal with non-place holder parts in that case. Eg. `This is the year %Y` is a valid strftime string, but `This is the year YYYY` is not a valid ICU pattern
* what should our fallback behavior be when the intl extension is not available?

We should keep in mind that our `dformat()` method is used by many plugins and it expects `strftime` placeholders

**Comment by splitbrain** [comment]
A composer package that provides strftime to IntllDateFormatter is available here: https://github.com/alphp/strftime 

But it still requires the intl extension.

**Comment by splitbrain** [comment]
An alternative gist (also using intl) is here https://gist.github.com/bohwaz/42fc223031e2b2dd2585aab159a20f30

**Comment by Klap-in** [comment]
> A composer package that provides strftime to IntllDateFormatter is available here: https://github.com/alphp/strftime
> 
> But it still requires the intl extension.

We use the intl extension already for sorting. So is having it here as dependency an issue? I saw you added already a fallback to that package above, however, it was placed in a branch. Is that already considered as complete enough?

**Comment by fiwswe** [comment]
Would just replacing `strftime` with `date` cause too many problems due to the potentially slightly different format syntax? (I have not done a detailed comparison of the syntaxes.)

`strftime` seems to used in:
* ./inc/common.php
* Several references (strings) in ./lib/plugins/config/lang/*/lang.php
* ./vendor/simplepie/simplepie/src/Item.php
* A number of plugins also use `strftime` but that would need to be dealt with in their projects

**Comment by splitbrain** [comment]
BTW. there is a converter for date<->strftime in struct: https://github.com/cosmocode/dokuwiki-plugin-struct/blob/master/meta/DateFormatConverter.php

(this is just a note for me, not a recommendation to use it)
