### ISSUE TITLE
Feature Request: Add xmlrpc function to create new users

### ISSUE THREAD

**Issue by satwareAG-ironMike** [dokuwiki/dokuwiki#3606]
**Why this could be useful:** 
3rd party applications that maintain user accounts would be enabled to create new wiki users without manual interaction. E.g. providing a centralized documentation platform with acl for a large number of users.

**Current workflow:**
Export users to csv and then import with usermanager mass import feature. After import the users acl are modified by the workflow using xmlrpc plugin.acl.addAcl . Deleting is also done via xmlrpc dokuwiki.deleteUsers

**Proposal:** 
Add dokuwiki.addUser xmlrpc function.
**Name:** dokuwiki.createUser
**Parameters:** (string)username, (string)fullname, (string)email, (array)groups, (string)password (optional),(boolean)send_mail 
**Description:** Adds a new user. When no password is provided the system generates a new one. When send_mail is true the user get's an account notification by mail.

**Comment by splitbrain** [comment]
I think it makes sense to add this. Pull Requests welcome.

Note:

> 3rd party applications that maintain user accounts

I would advise authenticating DokuWiki directly against that 3rd party app, instead of duplicating users across multiple applications.

**Comment by satwareAG-ironMike** [comment]
Since you tagged this request easy I've forked dokuwiki and will try to implement that feature.
Done so far:
- fork (easiest part ;)
- Prepare my local environment (PHPStorm, Docker Devops Images)
- phpunit up and running
- Dev runs local now with XDebug

I'm a bit uneasy now what code conventions I should follow and how to integrate the tests.
Since tests are running, I'll try a tests first approach...
![image](https://user-images.githubusercontent.com/59868837/150675123-ef34e275-01c4-4d68-bcab-95d0e8ada3ea.png)

I have no idea how long implementing that feature will take, since I have 1 morning of experience in dokuwiki's source code and I don't want to create a pile of mess (not in something vital as user creation).

I have not found a documentation how to contribute my code when done. Is there anything dokuwiki specific I should read before the pull request?

**Comment by Klap-in** [comment]
The unit tests for the coreapi calls are here. As example deleteuser, but there are more of course:
https://github.com/splitbrain/dokuwiki/blob/ba13c29839508a401a3a9b5bb4057dc6e50533c0/_test/tests/inc/remoteapicore.test.php#L453-L465
Note: it covers only correct input actually, no check of wrong input yet.

The function `triggerUserMod('create',...)` performs the creating of a user. Examples of implementation can help how to use it.
For examples see 

 * https://codesearch.dokuwiki.org/xref/dokuwiki/lib/plugins/usermanager/admin.php#697
 * https://codesearch.dokuwiki.org/xref/dokuwiki/lib/plugins/usermanager/cli.php#179
 * https://codesearch.dokuwiki.org/xref/dokuwiki/inc/auth.php#909

Please note that `triggerUserMod()` uses internally the `createUser()` function. Please do not use `createUser()` directly.

A code search can be done via Github, or via DokuWiki's code search (there you can add also search in plugins, to see usage in plugins): [only DokuWiki code](https://codesearch.dokuwiki.org/search?project=dokuwiki&full=triggerUserMod&defs=&refs=&path=&hist=&type=&xrd=1&nn=1) or [DokuWiki and plugins code](https://codesearch.dokuwiki.org/search?project=dokuwiki&project=plugin&full=triggerUserMod+create&defs=&refs=&path=&hist=&type=&xrd=&nn=2)

For the xmlrpc side:
https://codesearch.dokuwiki.org/xref/dokuwiki/inc/Remote/ApiCore.php#601
Please check canDo as well.

@splitbrain I miss the `$this->auth->canDo('delUser')` check in the deleteuser api. Should in the remote api calls, these cando not be checked as well?

**Comment by satwareAG-ironMike** [comment]
@Klap-in thank you for shedding some light on the dokuwiki core principles, that helped me a lot. I'm wondering if it would be better to just write a plugin for this functionality. My intention was to create the natural counterpart to the deleteUsers apicore call but the more I dive into the code the less I like the idea of me messing around with it - my knowledge of the code is a bit "shallow".
I got dokuwiki.createUsers working already but now I have to switch to `triggerUserMod` , missed that.

**Comment by Klap-in** [comment]
It can be a part of coreApi, because `triggerUserMod()` is a core function. 
btw, by using `$auth->triggerUserMod()` instead of `$auth->createUser()`, the event trigger is also triggered.

**Comment by Klap-in** [comment]
If you have a first proposal, you can open a PR. Then we have there a look together for eventually remaining parts.

**Comment by Klap-in** [comment]
`dokuwiki.deleteUsers` is a good first point to start, but for your `dokuwiki.createUsers` you have to add more input checking then happens there.
