### ISSUE TITLE
new release needed for newer versions of PHP

### ISSUE THREAD

**Issue by jamincollins** [dokuwiki/dokuwiki#3622]
The existing stable release of **dokuwiki** breaks under recent PHP releases, there are a few existing bug reports about this:
* #3399 
* #3470 

This impacts bleeding edge distributions, like Arch Linux.  I've also reported this to the Arch Linux bug tracker:
* https://bugs.archlinux.org/task/73658

**Comment by Klap-in** [comment]
We are stabilizing the current development version.
https://github.com/splitbrain/dokuwiki/projects/6
Of course a lot of volunteer work is involved, so due date is not available.
All testing feedback is welcome.

**Comment by jamincollins** [comment]
Why not a bug fix/update of the previous stable with only the two above patches?

**Comment by Klap-in** [comment]
I think there are more PHP 8 improvements? Or are these the only one that hit php8 users?

**Comment by michitux** [comment]
Are you sure this is an issue with the Arch Linux package? The [Arch Linux DokuWiki package](https://archlinux.org/packages/community/any/dokuwiki/) depends on the [php7 package](https://archlinux.org/packages/extra/x86_64/php7/) and therefore compatibility issues with PHP 8 should be irrelevant for it.

**Comment by jamincollins** [comment]
It may _depend_ on `php7`, but [Arch Linux php](https://archlinux.org/packages/extra/x86_64/php/) and [php-fpm](https://archlinux.org/packages/extra/x86_64/php-fpm/) are now **8.1.2-1** and I ran into this issue on my personal installation.

```
$ pacman -Q | grep -P 'php|dokuwiki'
dokuwiki 20200729-3
php 8.1.2-1
php-fpm 8.1.2-1
php-gd 8.1.2-1
php7 7.4.27-1
```

In my case, I need `php-fpm` for the setup through `nginx`.  I suspect others will hit the same issue I did.  I guess they _might_ be able to work around the issue by using `php7-fpm`, but I'm also pretty sure that isn't were they'll wind up given the error messages.  They'll likely find the above two patches (like I did) and get it working under `php-fpm`.

> are these the only one that hit php8 users?

From my experience the above patches are the only ones I needed.

**Comment by ryannathans** [comment]
PHP 7 is EOL - security updates end November 2022

**Comment by manikbh** [comment]
Just to upvote this issue: Ubuntu 22.04 LTS (current), has PHP8.1 by default. 
So right now I cannot port my old wiki to the new server (except using bad solutions, e.g. using development version or using an out-of-distribution older PHP package). 
A new stable version would be nice.

**Comment by Slarky** [comment]
I had the same issues on CentOS 9 Stream, where the default PHP version is 8.0 (so I'm pretty sure it'll also affect RHEL9 users). The error.log was spammed with

> 2022/06/11 18:19:33 [error] 32976#32976: *185 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in .../dokuwiki/vendor/marcusschwarz/lesserphp/lessc.inc.php on line 761" while reading response header from upstream, client: [...]

and also the DokuWiki pages looked weird (Search button text was off, rendering quoted text didn't work, 500er errors). It wasn't a pleasant experience.

FreeBSD also stopped building DokuWiki, see https://www.freshports.org/www/dokuwiki/

You have to change just 4 lines to make it work with PHP8, why isn't there a new minor release yet?

**Comment by jgod** [comment]
Can't `pkg install dokuwiki` - finds nothing

**Comment by Klap-in** [comment]
There is now a release candidate. No idea if the channels above mentioned consider release candidates? In that case it might be useful to notify them. We do not yet know when the stable release will be. Unfortunately, we as developers do not put effort in packaging for distributions due to limited resources.

**Comment by jamincollins** [comment]
I believe a new release is out now, and seems to resolve the issue. At least Arch is shipping: 20230404
