### ISSUE TITLE
PHP Warning:  Uninitialized string offset 0 in /var/www/wiki/public_html/inc/File/Resolver.php on line 55 / 60

### ISSUE THREAD

**Issue by controlcde** [dokuwiki/dokuwiki#3823]
After upgrading to **Igor** I´ve got the warning messages:

```
PHP Warning:  Uninitialized string offset 0 in /var/www/wiki/public_html/inc/File/Resolver.php on line 55
PHP Warning:  Uninitialized string offset 0 in /var/www/wiki/public_html/inc/File/Resolver.php on line 60
```
as @sromeroi described in #3728 it helps to replace:

> ```
>         // relative to current page (makes the current page a start page)
>         if ($id[0] === '~') {
>             $id = $this->contextID . ':' . substr($id, 1);
>         }
> 
>         // relative to current namespace
>         if ($id[0] === '.') {
> ```
> 
> with:
> 
> ```
>     protected function resolvePrefix($id)
>     {
>         // relative to current page (makes the current page a start page)
>         if (!empty($id) && $id[0] === '~') {
>             $id = $this->contextID . ':' . substr($id, 1);
>         }
> 
>         // relative to current namespace
>         if (!empty($id) && $id[0] === '.') {
> ```

But it needs a fix in this repo. I don´t know if this replacement is the fix ...

**Comment by splitbrain** [comment]
already fixed in c4055b85c837b6e07522adc69109b9fad9eb7c89
