### ISSUE TITLE
Call to undefined function splitbrain\PHPArchive\gzopen()

### ISSUE THREAD

**Issue by phil69210** [dokuwiki/dokuwiki#3867]
When I want to install the "note" plugin, I get the error :
```2023-01-31 17:23:35
Error: Call to undefined function splitbrain\PHPArchive\gzopen()
/volume1/web/dokuwiki/vendor/splitbrain/php-archive/src/Zip.php(212)
#0 /volume1/web/dokuwiki/lib/plugins/extension/helper/extension.php(1192): splitbrain\PHPArchive\Zip->extract('/var/services/w...')
#1 /volume1/web/dokuwiki/lib/plugins/extension/helper/extension.php(1001): helper_plugin_extension_extension->decompress('/var/services/w...', '/var/services/w...')
#2 /volume1/web/dokuwiki/lib/plugins/extension/helper/extension.php(641): helper_plugin_extension_extension->installArchive('/var/services/w...', false, 'lpaulsen93dokuw...')
#3 /volume1/web/dokuwiki/lib/plugins/extension/admin.php(141): helper_plugin_extension_extension->installFromUpload('installfile', false)
#4 /volume1/web/dokuwiki/inc/Action/Admin.php(33): admin_plugin_extension->handle()
#5 /volume1/web/dokuwiki/inc/ActionRouter.php(83): dokuwiki\Action\Admin->preProcess()
#6 /volume1/web/dokuwiki/inc/ActionRouter.php(48): dokuwiki\ActionRouter->setupAction('admin')
#7 /volume1/web/dokuwiki/inc/ActionRouter.php(60): dokuwiki\ActionRouter->__construct()
#8 /volume1/web/dokuwiki/inc/actions.php(16): dokuwiki\ActionRouter::getInstance(true)
#9 /volume1/web/dokuwiki/doku.php(126): act_dispatch()
#10 {main}
```

I [downloaded](https://www.dokuwiki.org/plugin:note) and selected the file "lpaulsen93-dokuwiki_note-2020-06-28-2-g86cd79f.zip".

DokuWiki version: Release 2022-07-31a "Igor"
PHP version 7.4.30
nginx server

**Comment by splitbrain** [comment]
Do you get the same error for other plugins? Is the gzip extension installed and enabled?

**Comment by splitbrain** [comment]
closing this because no additional info was provided

**Comment by phil69210** [comment]
Yes, you can close this issue. The problem was effectively related to the PHP libraries not linked yet. I add them and know it's ok.

**Comment by aquarios77** [comment]
On my synology there was a PHP74 serving the dokuwiki
1. I've created a file /volume1/web/test.php
`vi /volume1/web/test.php`
with the following content:
`<?php
phpinfo();
?>
`
and allowed it to be read and executed:
`chmod a+rx /volume1/web/test.php`

2. Navigated to it HTTP://<synology-ip>/test.php and verified the version of the PHP serving web
3. Aded to the file /volume2/@appstore/PHP7.4/misc/php-fpm.ini the following line:
`extension=zlib.so`
4. Restarted the PHP7.4 service to apply the change
5. Verified in HTTP://<synology-ip>/test.php
6. Updated the modules and the Dokuwiki itself
