### ISSUE TITLE
Page added notifications for changed pages

### ISSUE THREAD

**Issue by xrat** [dokuwiki/dokuwiki#3871]
The following was [posted yesterday at the forum](https://forum.dokuwiki.org/d/20801-page-added-notifications-for-changed-pages). @Michaelsy suggested that I open an issue.

We recently saw at least 2 occurrences where a subscriber received a "Page changed" notification followed by a "Paged added" notification for the same page shortly afterwards, about 50s later, even though revision histories and the `.changes` files show only the changes and no deletions or additions.

System: DokuWiki Release 2022-07-31a "Igor", PHP-FPM 7.3.31, Debian 10, Apache 2.4.38
Non-default plugins: commentsyntax 2019-11-28, move 2018-04-30

I was not able to reproduce the above but @Michaelsy [replied](https://forum.dokuwiki.org/d/20801-page-added-notifications-for-changed-pages/2) that he recently got several "Page added" nofitications from www.dokuwiki.org. Anyway, for now I can only add what I found in the logs of Apache and the mail system. Logs of DokuWiki were empty.

The following HTTP apparently caused a **Page changed** notification sent at 13:05:30 with Message-ID `<famlibrarynewsrev1675166729@...>`:

    13:05:29 "POST /wiki/fam/library/news HTTP/2.0" 302 -
    13:05:30 "GET /wiki/fam/library/news HTTP/2.0" 200 12110
    13:05:30 "GET /wiki/lib/exe/taskrunner.php?id=fam%3Alibrary%3Anews&1675166730 HTTP/2.0" 200 42

This was followed by a POST that caused **no notification**:

    13:06:17 "POST /wiki/fam/library/news HTTP/2.0" 200 10684
    13:06:17 "GET /wiki/lib/exe/taskrunner.php?id=fam%3Alibrary%3Anews&1675166777 HTTP/2.0" 200 42

And finally the following apparently triggered a **Page added** notification sent at 13:06:20 with Message-ID `<famlibrarynewsrev1675166729@...>`:

    13:06:20 "POST /wiki/fam/library/news HTTP/2.0" 302 -
    13:06:20 "GET /wiki/fam/library/news HTTP/2.0" 200 12109
    13:06:20 "POST /wiki/lib/exe/ajax.php HTTP/2.0" 200 - 
    13:06:20 "GET /wiki/lib/exe/taskrunner.php?id=fam%3Alibrary%3Anews&1675166780 HTTP/2.0" 200 42

The last 2 lines of `meta/fam/library/news.changes` are (redacted for privacy)

    1673875005      ipaddress  E       fam:library:news        username      summary                282
    1675166729      ipaddress  E       fam:library:news        username      summary                186

The UA strings in this case was `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`.

**Comment by xrat** [comment]
Note that the timestamp `1675166729` in the `.changes` file (and Message-ID) corresponds to `13:05:29` and hence the 1st POST shown above.

**Comment by xrat** [comment]
I am not a programmer but I tried to trace the tree of function calls that lead to `sendPageDiff()` where `!($rev)` is true and hence a newpage notification is sent. The only place I found is `saveWikiText()` in `inc/common.php` where `$rev` is actually potentially set via `(new PageFile($id))->saveWikiText($text, $summary, $minor)`. 

So, I wonder in how far this is related to #3781 where @splitbrain [found](https://github.com/splitbrain/dokuwiki/issues/3781#issuecomment-1411652780) that `filemtime()` can fail albeit rarely.

**Comment by xrat** [comment]
Apparently, I can now reproduce the bogus "page added" notifications in all of our installations: Simply click **Edit** and then **Save** without actually editing the content. Then, a notification is sent and (correctly so) no edit is listed in the revision history.

**Comment by Michaelsy** [comment]
> Simply click Edit and then Save without actually editing the content. 

:+1: 
 I was able to reproduce this behaviour the first time I tried it on dokuwiki.org (as a non-logged-in user).

\- Michael Sy.
