### ISSUE TITLE
PHP 8.1 warnung in JpegMeta.php - Undefined array key "value"

### ISSUE THREAD

**Issue by ste101** [dokuwiki/dokuwiki#3890]
I'm getting 
`Undefined array key "value" in xxx/wiki/inc/JpegMeta.php on line 1598` 
with PHP 8.1.

**Comment by breaker27** [comment]
I have the same issue after adding a new jpg file.
Workaround: I went to the Media Manager and entered a title and caption. Afterwards, the error messages at least didn't show up in the normal view of the wiki anymore.
But it seems to be a bug definitively.
