### ISSUE TITLE
Warning: Uninitialized string offset 2 in /home/robertinho/public_html/wiki/inc/fulltext.php on line 837

### ISSUE THREAD

**Issue by eduardomozart** [dokuwiki/dokuwiki#3896]
When searching for ``[[https://athiago.wordpress.com/2014/06/16/active-directory-entendendo-o-conceito-de-nested-groups-e-boas-praticas/|Nested Groups]]``, I'm receiving the following Warning on PHP 8.1:

``Warning: Uninitialized string offset 2 in /home/robertinho/public_html/wiki/inc/fulltext.php on line 837``

**Comment by mprins** [comment]
FWIW it's this line in main:

https://github.com/splitbrain/dokuwiki/blob/master/inc/fulltext.php#L848
