### ISSUE TITLE
Strange recent changes listing

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki#3898]
At https://www.dokuwiki.org/dokuwiki?do=recent
The following is listed:
![dokuwiki - Recent Changes  DokuWiki media&pages](https://user-images.githubusercontent.com/183250/220080525-c69e6ab0-b4cf-49fd-a71f-1ea1b8f33e21.png)
Less recent shows also only Unix time 0 entries.

only page shows a strange first result
![dokuwiki - Recent Changes pages ](https://user-images.githubusercontent.com/183250/220081516-c226a6b8-2c47-4276-95b9-b54dc35526b3.png)

Could someone with file access check the files used for these listings? I’m wondering what is going here.

**Comment by splitbrain** [comment]
Seems like the data/meta/_dokuwiki.changes contains a corrupted line at the end:

```
$> tail -n3 _dokuwiki.changes
1676850852      2a02:a44a:3b00:1:c8b:15a3:1729:aeef     R       devel:javascript        Klap-in old revision restored (2022-12-20 20:37)        16715650
59      852
1676851030      93.131.110.202  E       plugin:openid           [Discussion]            189
        84.237.55.63    C       кафедра_фундаментальной_и_прикладной_лингвистики_нгу    ellina  created         0
```

For some reason, the line is missing the timestamp.

I removed the last line and the list of changes is correct again. How this happened, I have no idea.

**Comment by splitbrain** [comment]
closing this until it happens again.
