### ISSUE TITLE
Windows (IIS) specific issue: slow farm host, fast animals 

### ISSUE THREAD

**Issue by jorbig** [dokuwiki/dokuwiki#3907]
I moved my Dokuwiki from Linux (Apache) to Windows (IIS), but now my farm host ([jhzwart.nl](url)) loads very slow, while my animals (like [bucanus.nl](url)) work totally fine. Whenever I rename my farm.ini to farm.ini.bak, the farm host loads fast, but that obviously breaks my animals. Any idea how to fix this?

My farm.ini looks like this:

```
[base]
farmhost = "jhzwart.nl"
basedomain = ""
farmdir = "C:\Users\jorik\Drive\Websites\jhzwart.nl\dokufarm\"

[notfound]
show = "farmer"
url = ""

[inherit]
main = 1
acronyms = 1
entities = 1
interwiki = 1
license = 1
mime = 1
scheme = 1
smileys = 1
wordblock = 1
users = 1
plugins = 1
userstyle = 1
userscript = 1
styleini = 1

```

**Comment by Michaelsy** [comment]
Since this is a support request, the [DokuWiki forum](https://forum.dokuwiki.org/) is better suited for this.

\- Michael Sy.

**Comment by jorbig** [comment]
You don't think it's a bug?

**Comment by Michaelsy** [comment]
> You don't think it's a bug?

I hadn't even thought of the idea that it could be a bug, since it runs on Linux. If it were a bug in DokuWiki, then it would depend more on the PHP version, which could also have changed with the server change.

\- Michael Sy.

**Comment by Michaelsy** [comment]
@splitbrain 
A question of understanding about the Farmer plugin. Is the farmer plugin necessary to run a farm? I have always thought that the Farmer plugin is essentially just a setup tool.

\- Michael Sy.

**Comment by jorbig** [comment]
> @splitbrain A question of understanding about the Farmer plugin. Is the farmer plugin necessary to run a farm? I have always thought that the Farmer plugin is essentially just a setup tool.
> 
> - Michael Sy.

Agreed, since it doesn't actually matter if the Farmer plugin is activated or not.

> > You don't think it's a bug?
> 
> I hadn't even thought of the idea that it could be a bug, since it runs on Linux. If it were a bug in DokuWiki, (or the Farmer plugin) then it would depend more on the PHP version (which could also have changed with the server change).
> 
> - Michael Sy.

Nope, in both cases the PHP version is 7.4.33. I do think the problem has to do with a bug in Dokuwiki's PHP scripting though. 
Maybe it has to do with the difference in folder structure between Windows and Linux, since the Farmer page shows some interesting differences there:

![image](https://user-images.githubusercontent.com/49766553/223487988-2215057e-e2c4-4176-9938-091502f88c72.png)

**Comment by splitbrain** [comment]
In any case, I don't think we can hope to find the reason for the slowdown with the information we have. Without debugging this on the affected machine to isolate the bottleneck, I wouldn't know what to do.

**Comment by Michaelsy** [comment]
By adding time stamps to PHP scripts that are written to a log, one could perhaps find out where the execution is slowed down.
Perhaps something can already be detected via the browser tools.

\- Michael Sy.

**Comment by splitbrain** [comment]
> it doesn't actually matter if the Farmer plugin is activated or not

Well, as soon as a farm is set up, the farm core is added to inc/preload.php and I guess that runs regardless of the plugin being enabled or not. One could consider that a bug.

But again since this problem only happens when the farm.ini exists and that is part of the farmer plugin this problem seems to be unrelated to the core and should be reported with the farmer plugin. I will close this issue here. Feel free to add new info to the ticket should it arise and point to a problem in the core.

BTW. hiring CosmoCode (authors of the farmer plugin) to debug this on your machine could be an option.

**Comment by jorbig** [comment]
Thanks for clearing that up. I guess for now I'll just leave my farm host unused, and use only animals instead. If anyone else has time to reproduce the problem and solve it, feel free of course ;-) I tried to debug it, but with allowdebug on, pages wouldn't load at all...

**Comment by Michaelsy** [comment]
>  I tried to debug it, but with allowdebug on, pages wouldn't load at all...

You don't necessarily need the allowdebug option (TBH, I don't actually know what function is associated with it...). I have always done debugging by simply modifying the PHP scripts.

\- Michael Sy.

**Comment by jorbig** [comment]
I finally found out the problem. The folders that needed write permissions, must have full permissions (not just write).
@splitbrain: https://www.dokuwiki.org/install:permissions#windows_using_microsoft_iis is misleading in this regard. A lot of people have encountered the same problem as me (just google for 'dokuwiki slow windows'), and possibly not found the solution.

**Comment by splitbrain** [comment]
@jorbig Interesting. I have no idea why this is, but Windows is weird. Can you update the documentation please?

**Comment by jorbig** [comment]
I just did. 'Full Control' won't be necessary, but 'Modify' access is required to fix the slowness problem.
