### ISSUE TITLE
Warning: Undefined array key "value" in inc/JpegMeta.php on line 1599

### ISSUE THREAD

**Issue by eduardomozart** [dokuwiki/dokuwiki#3909]
Hello,
When uploading the following photo to Wiki (available at: https://www.qnapbrasil.com.br/blog/post/o-que-e-virtualizacao):

![hypervisor-post-o-que-e-virtualizacao-qnapbrasil](https://user-images.githubusercontent.com/2974895/223811789-f325c047-f410-431d-9596-f0f43f6619ff.jpeg)

And clicking on it, the media manager throws the following error:

![image](https://user-images.githubusercontent.com/2974895/223814557-7c822cc3-caec-490c-a850-71f2b461af35.png)

It seems to be related to the following line: https://github.com/dokuwiki/dokuwiki/blob/f1892550e3e471118e1a936b79e3c729af7ea449/inc/JpegMeta.php#L1598

When dumping the array with ''var_dump($values[$i])'', the following is shown:

```
array(4) { ["tag"]=> string(17) "xmpMM:DerivedFrom" ["type"]=> string(8) "complete" ["level"]=> int(4) ["attributes"]=> array(2) { ["stRef:instanceID"]=> string(40) "xmp.iid:59EF7D81F91511EAB83E83782B894E0E" ["stRef:documentID"]=> string(40) "xmp.did:59EF7D82F91511EAB83E83782B894E0E" } }
```

It didn't seem to have a ``$values[$i]['value']``, so setting it to the ``$meta`` variable throws a warning on PHP 8.1 on DokuWiki Release 2022-07-31a "Igor" (Stable). It seems to happens only with JPEG images (as the filename states). This error isn't shown when opening PNG files.

**Comment by Michaelsy** [comment]
Duplicate of: #3890 

\- Michael Sy.

**Comment by eduardomozart** [comment]
Oh, I see. I didn't found any information about this bug on the Internet so I decided to open this bug report. Thank you. I'll close this bug report.
