### ISSUE TITLE
Log Viewer runs into OOM

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#3919]
When logfiles get especially large, the logviewer fails to display them because of memory restrictions. It would make sense to only partially load large logfiles (from the end) and display a warning

**Comment by Adibzadeh** [comment]
Hi, I would like to work on this, can you assign me?

**Comment by Adibzadeh** [comment]
Just to be clear and on the same page, when you say large logfiles, how much is considered "large"? I'm thinking about log files larger than 1mb (maybe?) at this point it has approximately 15,000 lines, but I would like to know your opinion as well.

P.S: I'm  also thinking about adding a button when the log is large so the user can be redirected to a new page and see the raw logs on there (large ones) or click and use the "save as" option to download it.

**Comment by Adibzadeh** [comment]
The project currently uses `file()` function which reads the entire file into memory and make an array out of it and _then_ prints it out into the browser, this function is also a little disastrous when it comes to large files. I think it also can be improved by using `fopen()` so the file be wrote line by line into the buffer and then sent to the user.

**Comment by splitbrain** [comment]
> when you say large logfiles, how much is considered "large"

I had a 1.4GB log file here ;-)

> see the raw logs on there (large ones) or click and use the "save as" option to download it.

A raw download seems like a good idea.

> currently uses file()

Yes. That needs to be replaced. TBH reading the last 1500 or so lines should be more than enough and probably still can be handled in memory. My approach would be to use fopen() to read the last X kb of the file into memory, convert it into lines, skip the first line (which is most likely incomplete), skip all indented lines at the beginning (which belong to a previous header) and then output the remaining lines.

**Comment by Adibzadeh** [comment]
Thank you. Based on your answer, I think the PHP default memory limit in here is a good option and limit for most users. If the logfile was larger than **128MB** we just show the end of it.
Do you agree?

In future, we can make this more dynamic and add a settings option for advanced users so they can choose the limit based on their server needs and available hardware.

**Comment by splitbrain** [comment]
no. please keep this simple.

**Comment by Adibzadeh** [comment]
@splitbrain 
This is my first contribution in OSS, and I'm still learning, if there's any issue in my workflow, or any possible improvement (commit message, PR comment, etc...), I would really appreciate it if you tell me and I'll try to improve it.
Thank you so much.
