### ISSUE TITLE
ACL manager - table column headers sort function (like sortablejs or datatables plugin)

### ISSUE THREAD

**Issue by Chris75forumname** [dokuwiki/dokuwiki#3921]
ACL manager in the admin section - configuration manager - the ACL table needs a column headers sort function (like sortablejs plugin or DataTables)
https://github.com/FyiurAmron/sortablejs
https://datatables.net/

**Comment by splitbrain** [comment]
ACLs are evaluated by ID proximity, then user/group membership. Rules are sorted in the same way. There isn't much sense in sorting them differently.

**Comment by Chris75forumname** [comment]
Yes there is, by user/group! Since I found an easy way, I post it here for others to use:

1. install the plugin https://www.dokuwiki.org/plugin:sortablejs
2. put following line of code into your /dokuwiki/conf/userscript.js:

       jQuery("div#acl_manager div.table").addClass('sortable');

Now you get sortable headers. You can now sort the ACL table by user/group by clicking on the header of this column.
Reference: https://www.dokuwiki.org/devel:plugin_programming_tips#adding_javascript
