### ISSUE TITLE
"Your DokuWiki password" messages lack 1st char of name in To:

### ISSUE THREAD

**Issue by xrat** [dokuwiki/dokuwiki#3923]
On my 2 main systems, both running DokuWiki v2022-07-31, Debian 11, PHP 7.4, one w/ Sendmail, one w/ msmtp+Postfix, the mail message which notifies new users about their newly created accout ("userdata") lacks the 1st letter in the Name of the user in the `To:` mail header. Say, I created an account for "Anon Ymous", the message sent has the following headers

```
Date: Tue, 14 Mar 2023 16:03:41 +0100
From: DokuWiki Changes <webadmin@example.net>
To: non Ymous <anonymous@example.net>
Subject: [DokuWiki] Your DokuWiki password
```
The "A" is missing.

**Comment by splitbrain** [comment]
That's super weird. I can't reproduce this.

**Comment by xrat** [comment]
My apologies! I can only reproduce it for names starting with "t", even "T" is not removed.

**Comment by xrat** [comment]
I think I found it: It's an obvious quoting mistake in `getCleanName()` in `inc/Mailer.class.php`, isn't it?

Sorry, that I don't know how to do pull requests or similar.
