### ISSUE TITLE
Polish letter Ł is replaced by undescore in filenames, should be L

### ISSUE THREAD

**Issue by slotwin** [dokuwiki/dokuwiki#3924]
With settings
fnencode=url
deaccent=1

polish letter Ł and ł are replaced by underscore in filenames. They should be replaced by L and l. All the other polish letters ąćęóńźż are replaced by their corresponding unaccented characters. All of them are in lookup tables in inc/Utf8/tables, including Ł and ł.

This is similar to problem described [here](https://bugs.dokuwiki.org/164.html) but that seems to long be fixed.

Ł is 0x0141
ł is 0x0142

It is generally expected to be deaccented (at least in my opinion and from my experience).

DokuWiki Release 2022-07-31a "Igor"

**Comment by Klap-in** [comment]
deaccenting is happening in the cleanID().
https://codesearch.dokuwiki.org/xref/dokuwiki/inc/pageutils.php#120-164
as there are more steps I wonder if deaccenting is causing this.

Existing tests:
https://github.com/dokuwiki/dokuwiki/blob/master/_test/tests/inc/pageutils_clean_id.test.php

**Comment by splitbrain** [comment]
I can't reproduce the issue. I added a test, that succeeds. I also tried it here: https://www.dokuwiki.org/playground:test

@slotwin can you provide any additional info to reproduce this?

**Comment by Michaelsy** [comment]
> I can't reproduce the issue. 

It's about filenames?

\- Michael Sy.

**Comment by splitbrain** [comment]
> It's about filenames?

![screenshot-www dokuwiki org-2023 03 16-08_41_56](https://user-images.githubusercontent.com/86426/225548194-0c3f82e3-0a2a-49cb-9af3-f6fc0f60e452.png)

Looks fine to me?

**Comment by slotwin** [comment]
Embarrassing. Stupid me.

It was all catlist plugin fault. I use its 'Add page' button on the tree list to place new pages directly where I want them. It has an option to sanitize filenames before creating new pages but I didn't realise it has its own function to do it.

It works fine when I add pages standard way. Sorry for the noise.
