### ISSUE TITLE
Set noindex on pages with search parameter

### ISSUE THREAD

**Issue by ste101** [dokuwiki/dokuwiki#3926]
Pages with `&s[]=` have the meta tag `<meta name="robots" content="index,follow">` and can get indexed.
Please set `<meta name="robots" content="noindex,nofollow">` if a search parameter is present in the url.

**Comment by splitbrain** [comment]
Can you explain the rationale? Shouldn't be the canonical header be enough?

**Comment by fiwswe** [comment]
@ste101 Why shouldn't these pages be indexed? If you publish a link with a search parameter somewhere then having a search engine follow that link and index the result would be perfectly fine IMHO.

**Comment by ste101** [comment]
@splitbrain 
You are right. In Google search console these links are shown in category 'Alternate page with proper canonical tag'.
So there is no need to change this.
