### ISSUE TITLE
Inline <php> and <html> no longer working with Release 2023-04-04 "Jack Jackrum"

### ISSUE THREAD

**Issue by PifPof73** [dokuwiki/dokuwiki#3945]
Hi, 
I just updated to "Jack Jackrum" with php 8.1.
We used the inline <html> </html> and <php> </php> option to add some additional infos to the wiki, but these parts are no longer parsed and the option to activate it is gone in the config.
I tried to get the result with phpwikify, but the result is not well formatted.

Can we please get the features back?
Regards,
PifPof73

**Comment by splitbrain** [comment]
please read the changelog before upgrading

**Comment by PifPof73** [comment]
Yes, I know. And I downgrade our installation again.
But we need this feature - why is it removed and are there alternatives?

**Comment by PifPof73** [comment]
> please read the changelog before upgrading

Closing my request with this comment is some sort of showing me your middle finger ... thanks for nothing.

**Comment by splitbrain** [comment]
> thanks for nothing

You're welcome to nearly 20 years of development, maintenance and support of nothing.

**Comment by fiwswe** [comment]
If you where using `<php>` or `<html>` on a wiki where potentially untrusted/incompetent people were allowed to edit then this change fixes a serious security issue for you. (Just imagine someone embedding a PHP script on a wiki page that recursively deletes everything that is writable by PHP for example. Not-a-good-thing™!)

OTOH if you are on a private wiki where **ALL** editors are trusted and competent then this is a serious bummer. I'm in this situation as well and I am in the process of writing a plugin to replace this functionality for those cases where the security implications are managed. I may publish this plugin when I'm done.

For PHP you can consider using [PHP Wikify](https://www.dokuwiki.org/plugin:phpwikify) as you have done. However its feature is that the output gets parsed as wiki source code. So it is more of an alternate than a direct replacement. If you don't want this then you are currently out of luck.

For HTML you might consider the [Ad-Hoc Tags Plugin](https://www.dokuwiki.org/plugin:adhoctags). It may have enough functionality to replace what you did with `<html>`. You will need to touch all wiki pages where you used `<html>` though.

**Comment by PifPof73** [comment]
Hi fiwswe,
thanks for being more constructive.

I use a private closed wiki with "normal users" just reading (classical inter wiki inside the company), so I do not see any security issues (I totally agree that this feature should never be used in a public open wiki, which is not my use case).

I tried PHP Wikify after upgrade, but - as you said - the output is not formatted well (I tested it with phpinfo()).
I will check Ad-Hoc Tags Plugin, but we use iframes on some places (I know, not the best choice).

Removing a "killer feature" running since several years without giving some information about the "whys" and "howto else" is really frustating for me, but surely up to the contributor group. They seem to have not all use cases in their minds or they just don't care. 
If it is related to security than it is strange, that it was ok for the last decade - but I am not here to judge, I just want to keep my loved wiki alive ...

I am happily waiting for your plugin.
Regards,
PifPof73

**Comment by mprins** [comment]
@PifPof73 this discussion was conducted in multiple channels almost 6 months ago, you are late to the party.
see:
- https://github.com/dokuwiki/dokuwiki/pull/3798
- https://forum.dokuwiki.org/d/20628-after-igor-htmlok-and-phpok-will-no-longer-be-included-in-the-dokuwiki-core

**Comment by PifPof73** [comment]
> @PifPof73 this discussion was conducted in multiple channels almost 6 months ago, you are late to the party. see:
> 
>     * [Remove the htmlok and phpok embedding options #3798](https://github.com/dokuwiki/dokuwiki/pull/3798)
> 
>     * https://forum.dokuwiki.org/d/20628-after-igor-htmlok-and-phpok-will-no-longer-be-included-in-the-dokuwiki-core

@mprins missed that - thanks for the info!

**Comment by PifPof73** [comment]
Hi,
just to confirm:
I installed the **htmlok** Plugin from saggi [https://www.dokuwiki.org/plugin:htmlok](url), which let you enable / disable both php and html (like in the old core).
I upgraded to _Jack Jackrum_ and all my Inline php and html is running exactly like before.
Regards,
PifPof73

**Comment by licsber** [comment]
just install htmlok plugin and REPLACE ALL <html> WITH <HTML> WORK.
thanks for wasting my 2 hours (but thanks for maintain this app decades
