### ISSUE TITLE
Create github actions workflow for release bump

### ISSUE THREAD

**Issue by glensc** [dokuwiki/dokuwiki#3951]
So developers can easily automate keeping plugin info txt in sync and have matching git tags:
- https://github.com/ssahara/dw-plugin-commentsyntax/issues/13
- https://github.com/Dric/dokuwiki-titlesanchorlink/issues/7
- https://github.com/dokufreaks/plugin-discussion/issues/338

In my mind the workflow would be like this:
1. monitor changes to `*.info.txt` (include templates as well)
2. skip if version line is unchanged or git tag exists
3. create git tag and push it

the workflows could be hosted in dokuwiki org and re-used by plugins:
- https://docs.github.com/en/actions/using-workflows/sharing-workflows-secrets-and-runners-with-your-organization
- https://docs.github.com/en/actions/using-workflows/reusing-workflows

**Comment by Klap-in** [comment]
@splitbrain has already an script that automatically made updates of the plugin wiki page. I do not remember were it stays, maybe Andi can shine some light on this?
Probably here things can be combined?

**Comment by glensc** [comment]
updating wiki as well could be bonus indeed.

**Comment by Klap-in** [comment]
Pardon, miss click.

**Comment by Klap-in** [comment]
This is his tool, it create tags when updating versions https://github.com/splitbrain/dokuwiki-versionfix

**Comment by glensc** [comment]
Created something:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/pull/12

**Comment by glensc** [comment]
Also integrated the versionfix:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/pull/19

Here's a release with both of them:
- https://github.com/glensc/dokuwiki-plugin-slacknotifier/actions/runs/4715533585/jobs/8362584921

**Comment by Klap-in** [comment]
As mentioned in #3966, this is interesting to add to https://github.com/dokuwiki/github-action
