### ISSUE TITLE
"Undefined array key "media" in inc/ChangeLog/RevisionInfo.php on line 39" in 2023-04-04 "Jack Jackrum"

### ISSUE THREAD

**Issue by gturri** [dokuwiki/dokuwiki#3958]
Hi,

Since I upgraded to 2023-04-04 "Jack Jackrum" and I know observe php warnings when I'm prompted to recover a draft

**Steps to reproduce**
- From an artbitrary page of your wiki: edit a page, make some changes, make sure the changes are autosaved, and then close your tab without saving your changes (ie: make sure there is an open draft for that page)
- Go back to that page and select `Edit draft`

**Expected behavior**
I expect to land on the page `Draft file found` and that it shows no error or warnings

**Actual behavior**
The page `Draft file found` has the expected content but also the warning `Warning: Undefined array key "media" in /xxx/inc/ChangeLog/RevisionInfo.php on line 39`

The stacktrace is:
```
{main}( )	.../doku.php:0
act_dispatch( )	.../doku.php:126
include( '/var/www/html/wikiDev/lib/tpl/dokuwiki/main.php )	.../actions.php:27
tpl_content( $prependTOC = ??? )	.../main.php:59
dokuwiki\Extension\Event::createAndTrigger( $name = 'TPL_ACT_RENDER', $data = 'draft', $action = 'tpl_content_core', $canPreventDefault = ??? )	.../template.php:85
dokuwiki\Extension\Event->trigger( $action = 'tpl_content_core', $enablePrevent = TRUE )	.../Event.php:199
[call_user_func_array:{/xxx/inc/Extension/Event.php:133}](http://www.php.net/function.call-user-func-array:%7B/var/www/html/wikiDev/inc/Extension/Event.php:133%7D)( $callback = 'tpl_content_core', $args = [0 => 'draft'] )	.../Event.php:133
tpl_content_core( 'draft' )	.../Event.php:133
dokuwiki\Action\Draft->tplContent( )	.../template.php:100
dokuwiki\Ui\PageDraft->show( )	.../Draft.php:40
dokuwiki\Ui\PageDiff->compareWith( $text = '<nspages >' )	.../PageDraft.php:35
dokuwiki\ChangeLog\RevisionInfo->__construct( $info = ['date' => 1675800528, 'ip' => '127.0.0.1', 'type' => 'E', 'id' => 'sandbox:00-index', 'user' => 'guillaume', 'sum' => '', 'extra' => '', 'sizechange' => -46] )
```

**Comment by dregad** [comment]
I'm affected by this as well. Occurs on latest master too (6de7d28d1d24e64f46b171fd38e770430b5af6f2).

**Comment by dregad** [comment]
This can easily be fixed with the following patch

```patch
diff --git a/inc/ChangeLog/RevisionInfo.php b/inc/ChangeLog/RevisionInfo.php
index 43bc8c66f..e4d6990b2 100644
--- a/inc/ChangeLog/RevisionInfo.php
+++ b/inc/ChangeLog/RevisionInfo.php
@@ -36,7 +36,7 @@ class RevisionInfo
     {
         if (is_array($info) && isset($info['id'])) {
             // define strategy context
-            $info['mode'] = $info['media'] ? 'media' : 'page';
+            $info['mode'] = ($info['media'] ?? false) ? 'media' : 'page';
         } else {
             $info = [
                 'mode' => 'page',

```

But maybe it would be more appropriate to ensure the `media` key is always defined in the $info array ?

**Comment by Klap-in** [comment]
> But maybe it would be more appropriate to ensure the `media` key is always defined in the $info array ?

Ah, indeed, PageDiff::compareWith() does not set the `media` entry. That is something to improve here. I'm bit surprised that the `media` entries need to be set manually everywhere. Maybe that can set from the class as well...
