### ISSUE TITLE
Recent Changes link to media / Revisions

### ISSUE THREAD

**Issue by HMJR** [dokuwiki/dokuwiki#3960]
Today an edited page shows in Recent Changes a link like this:
https://site/wiki/pagename?tab_details=view&ns=wiki&image=wiki%3Apagename&do=media
instead of https://site/wiki/pagename
Revisions of the page are listed but only available when compared.
DokuWiki Release 2022-07-31a "Igor" Writr template PHP 8.0

Regards,
Henk M.

**Comment by Klap-in** [comment]
This is the link that should be used for the media(images etc) in your Recent Changes list.
Does this happen for all your pages and all your media in the Recent Changes list?
Does the page name (or namespace) still contain other characters than letters or numbers?

**Comment by HMJR** [comment]
The first time this happened was on April 8 when creating a new page https://site/wiki/lapalma_s.r.l. I made a post about this issue https://forum.dokuwiki.org/d/20986-recent-changes-link-to-media.
After that a few dozen more pages were made and changed as usual. Yesterday we had the same problem after modifying the page https:/site/wiki/vitra_nederland_b.v. 
I can send you the links to both so you can see for yourself. Thank you in advance for your help.
Regards, Henk M.

**Comment by saggi-dw** [comment]
#3613, fixed with "Jack Jackrum"

**Comment by HMJR** [comment]
So if we don't want to update to "Jack Jackrum" now

In File inc/ChangeLog/RevisionInfo.php:
39 # $info['mode'] = strrpos($info['id'], '.') ? 'media' : 'page';
40 $info['mode'] = $info['media'] ? 'media' : 'page';

is the solution?

**Comment by Klap-in** [comment]
@HMJR the examples you provide are all cases where the page name includes a dot. As stated by @saggi-dw this is solved in the latest version (Jack Jackrum) of DokuWiki. Please update, or fix temporary manually the `inc/ChangeLog/RevisionInfo.php` file.
