### ISSUE TITLE
[Feature Request] Provide wiki code headings with their own class

### ISSUE THREAD

**Issue by Michaelsy** [dokuwiki/dokuwiki#3963]
Hello esteemed development team!

It would be very helpful for me if ~~the content area headers~~ the standard headings of the wiki code were provided with their own CSS class (e.g. `.wiki-header`).

For several reasons I format ~~the content headers~~ the standard headings of the wiki code in sometimes very specific ways. Formatting that makes no sense elsewhere where hx elements appear in the HTML code.

Unfortunately, this is the case in many places (e.g. headings of admin pages, also plugins use hx-elements) and it is quite time-consuming and confusing not to have my special formattings applied to all these other headings.

Many thanks in advance for the help, I really appreciate it!

\- Michael Sy.

**Comment by Michaelsy** [comment]
No, this addresses all `h3` that are within `#dokuwiki__content`.(E.g. the heading of the TOC is an h3 element.) But I want to specifically address only those that are inserted into the wiki code via the syntax `==== myHeading ====`.

\- Michael Sy.

**Comment by fiwswe** [comment]
All `==== Header ====` elements are immediately followed by a `<div class="levelx">` element (where `x` is a number designating the level of the header). You may be able to use that for CSS identification of the `<hx>` elements.

Something like:
```css
#dokuwiki__content h3:has(+ div.level3) {
  color: red;
}
```
Might depend on your template though. I tested the above on DW 2023-04-04 "Jack Jackrum" using [sprintDoc Template](https://www.dokuwiki.org/template:sprintdoc).

**Comment by fiwswe** [comment]
PS. If you need to address a specific header then you may be able to use the `sectioneditNNN` classnames or its `id` attribute to identify the header.

Consider this wiki page for example (uses the [htmlok Plugin](https://www.dokuwiki.org/plugin:htmlok), use only on private wikis, read the security warnings):
```
====== Test custom header CSS ======

<HTML>
<style type="text/css">
#dokuwiki__content h3:has(+ div.level3) {
  color: red;
}
#dokuwiki__content h3.sectionedit3 {
  color: green !important;
}
</style>
</HTML>

===== H2 Header A =====


==== H3 Header A1 ====


==== H3 Header A2 ====


===== H2 Header B =====


==== H3 Header B1 ====


==== H3 Header B2 ====

```

**Comment by Michaelsy** [comment]
@fiwswe Thanks for the suggestions, but...

> `:has()` pseudo class

[browser support](https://caniuse.com/css-has) is unfortunately insufficient. (Besides, I resort to such an unsightly syntax only when there is no other option.) 

> `#dokuwiki__content h3.sectionedit3 {`

the `.sectioneditN` class is not present in every case.

> id attribute 

the id attribute is useless for my purposes, because it depends on the content of the headline.

\- Michael Sy.

**Comment by fiwswe** [comment]
> [browser support](https://caniuse.com/css-has) is unfortunately insufficient.

Yeah, Firefox and IE are out. But for me that is irrelevant ;-) I'm happy if Safari (Webkit) and Chrome work correctly. YMMV


> such an unsightly syntax

Well you didn't specify that you only wanted to use trivial CSS ;-) There are much more complex CSS examples than `:has()`. I find the `:has()` pseudo element to be very useful and not overly complex.

Your other comments depend on your exact use case. But I agree the issues you mentioned might be relevant.


I'm still unclear which use case you want to address:

1. Target all header elements generated by the wiki syntax at a certain depth?
2. Target a specific header element only?
3. For all pages or just for a specific page?

Where would the content of a wiki page, i.e. the content of ` #dokuwiki__content`, contain `h3` elements that are **_not_** generated by `==== Header ====` syntax? I.e. why would `#dokuwiki__content h3 { … }` not work for you? In my estimation that could only happen if you insert custom HTML (using a plugin) or more generally if some plugin inserts `h3` elements. I don't think DokuWiki itself can do this. But maybe I am missing something here?

**Comment by Michaelsy** [comment]
@fiwswe Sorry, I can't quite make sense of your questions. As far as they are relevant, I think they are already answered above.

\- Michael Sy.

**Comment by Klap-in** [comment]
Alternative is to made your own renderer plugin (have a look at the plugin wizard for an quick start point), that extends the default xhtml renderer to override the header function with a function that generates all classes you need. (note, only one renderer can be active at a moment.) 
Futher, if plugins are using the header() function, these will get the extra classes as well. So I'm wondering if your case can be solved.

I'm wondering if there is any use case outside this, what it made worth implementing for everybody. With other words, the use case is actually not that clear for me.

**Comment by Michaelsy** [comment]
Very concretely, I want this selector: 

```
div#dokuwiki__top:not(.notFound):not(.mode_admin):not(.mode_index):not(.mode_recent):not(.mode_revisions):not(.mode_diff):not(.mode_backlink) 
.page.group > h1, 
.page.group .section_highlight > h1, 
div.preview > div.pad > h1,
.plugin_wrap > h1, 
.plugin_include_content > h1 {
    ...
}
```

be able to replace with this one:

```
h1.wiki-header {
    ...
}
```

Because of the five possible heading levels, the whole thing must also be multiplied by five. (However, this can be done with LESS.)
\- Michael Sy.

**Comment by fiwswe** [comment]
@Michaelsy I think I understand your intent now. Sorry for not reading your original post thoroughly enough.

Given that admin plugins use the same internal functions to generate headers as the `==== Header ====` syntax on pages, modifying the later to include a class will not work or be overly complicated.

How about adding some attribute on a container that is used only on wiki pages, not on admin pages or the like? Maybe such a container already exists or maybe it would need to be added. Come think of it the following already exists and seems to work and ist much simpler than the CSS you posted:

```css
.mode_show div.page h2,
.mode_preview div.page h2 {
  color: red;
}
```
or
```css
.mode_show #dokuwiki__content h2,
.mode_preview #dokuwiki__content h2 {
  color: red;
}
```

The `.mode_preview …` selector is needed so that the previews look the same as the final page.

**Comment by Michaelsy** [comment]
Let me ask it another way:
My guess is that there is a single place (or maybe a few) in the PHP code where adding the class would occur. Does anyone have a suggestion as to which place that might be? If so, I would check it out and see if that covers my use case.

\- Michael Sy.

**Comment by fiwswe** [comment]
The place where the class for header tags is added seems to be:
https://github.com/dokuwiki/dokuwiki/blob/94ce2489c4227b41d1cbf6ef4257face8810987b/inc/parser/xhtml.php#L247-L248

You could change that to, e.g.:
```php
            $header .= ' class="dw-header '.$this->startSectionEdit($pos, $data).'"';
        } else {
            $header .= ' class="dw-header"';
        }
```

But that would affect all header tags, those on wiki pages as well as those on admin pages.

**Comment by Michaelsy** [comment]
> The place where the class for header tags is added seems to be:

Thanks!

Ok, if this function is called from countless places (and that seems to be the case), then at least I have some idea of the difficulty.

What I can think of would be to add an optional parameter through which one could add an optional class. It could probably look something like this (sorry if there's something wrong with it, my PHP knowledge is quite rudimentary):

`public function header($text, $level, $pos, $returnonly = false, $class = "" ) { ... } `

But I can't get any further from there. Now I would have to get to the point where the renderer is called to render a wiki code header. I only have a very vague idea of where and how this happens.

\- Michael Sy.

**Comment by fiwswe** [comment]
I still think you are going about this the wrong way.
* Your solution would be specific to headers. Someone else might want to target different elements on wiki pages only.
* The extra parameter to the `header()` method only shifts the problem to the callers.

What you seem to need is a way to differentiate wiki page content from other content in CSS.

If you don't like my suggestions (`.mode_show`, `.mode_preview`) you could think about putting your page content into a block level element produced by some plugin that allows nesting other content. Apart from producing a CSS-identifiable block element, this plugin would not need to have any visual impact. (However that approach may not work well in the preview case, when editing a section contained inside the block).

I think you could do this using the [wrap Plugin](https://dokuwiki.org/plugin:wrap) and a custom style that makes the plugin _invisible_. E.g.:
```css
.dokuwiki div.wrap_wiki {
  /* Nothing here on purpose. */
}
```
Use it like this:
```
<WRAP wiki>
Your page content.
</WRAP>
```
Then you can target your headers like this:
```css
.wrap_wiki h3 {
  color: red;
}
```

**Comment by Michaelsy** [comment]
If you include headings in wraps, then there  is no longer an edit section inserted at that point. This is a limitation of the Wrap plugin. Incidentally, the effort involved in this solution would exceed the benefit many times over.

----

> If you don't like my suggestions (.mode_show, .mode_preview) 

I have no problems using these classes. My selector has developed an unnecessary "appendix vermiformis" through a long historical development. It started with a single harmless not-statement and became longer and longer without me having the idea to wind up the basic one differently.

----

The reason why `header()` is also called on admin pages is that they also (surprisingly) work with wiki code. See https://github.com/dokuwiki/dokuwiki/blob/master/inc/lang/en/admin.txt

Therefore, I currently assume that one could enter the `.wiki-header` class directly into the `header()` function and only have to check there whether the current page is rendered in show or preview mode.

\- Michael Sy.

**Comment by fiwswe** [comment]
> If you include headings in wraps, then there is no longer an edit section inserted at that point.

True, I had not checked that. This was more of an easily tested example of how a plugin might be used to implement a CSS-identifiable container.

> I have no problems using these classes.

So what is the actual remaining issue then?

**Comment by Michaelsy** [comment]
>> I have no problems using these classes.

> So what is the actual remaining issue then?

Sorry, I have expressed myself in a somewhat misleading way. I can use these classes (they are of course better than my endless string of not-statements). But I would like to avoid it in principle.

But given the overall situation as I understand it, that's probably not a sensible objective. It seems most sensible to me now to insert the `.wikiheading` class via the `header()` function and fix the admin page matter separately afterwards via CSS. This is not the perfect solution, but it is a viable one.

\- Michael Sy.

**Comment by Michaelsy** [comment]
>  to insert a `.wikiheading` class via the `header()` function 

@splitbrain  Would a corresponding PR be committed?

\- Michael Sy.

**Comment by splitbrain** [comment]
As @fiwswe pointed out, nearly all headers in the wiki are created by wiki parser/renderer. That can be in the main page, the sidebar, most of the introduction texts on special pages, plugins, etc.

There is no difference in addressing `.dokuwiki.mode_show .page h1` to a potential `.dokuwiki.mode_show h1.wikiheading`.

You also still haven't explained your actual usecase of why in-page headers should be styled differently from the rest - which sounds questionable from a design and accessibility standpoint anyway.

So I don't see a reason to clutter the HTML with an additional class.

**Comment by Michaelsy** [comment]
> There is no difference in addressing `.dokuwiki.mode_show .page h1` to a potential `.dokuwiki.mode_show h1.wikiheading`.

These are just two counterexamples out of many possible ones:
The first selector pattern selects the h3 element of the TOC, while the second one does not.
The Subjectindex plugin uses all HTML heading levels from h1 to h5(h6) and all of them are selected by the first selector pattern, while the second one does not.

> You also still haven't explained your actual usecase

It's not about optimizing the DokuWiki core for my specific use case, and whether this use case is justified or not. (Actually, the latter cannot be the subject at all, especially not in matters of design.) The key point is a more general one: Just as it is common practice for good reason to label the HTML code of plugins with a plugin-specific class, the same should be done for the group of headings of wiki code. This way, this group can be specifically formatted if necessary or desired, for whatever reason.

The fact that I want to make further distinctions beyond this is not relevant in this context. (And I had already removed this issue from my wishlist.)

\- Michael Sy.

**Comment by splitbrain** [comment]
We usually add features when we have a good use case for it. Because otherwise we start to clutter the code with stuff nobody uses. Because why stop at headings? Why not add a class to all `<b>` tags? Or `<p>`?

**Comment by Michaelsy** [comment]
> Why not add a class to all `<b>` tags? Or `<p>`?

Simply because no one has reported any problems with it so far.

The fact is that the only particularity of my use case is that my headings are formatted in a slightly more complex way (more properties are set) than is usual in many cases. (Not so much for aesthetic reasons, but for practical reasons, (my authoring tool)) Templates that have a comparable formatting, such as Bootstrap3 or Strap/Combostrap, also provide their wiki headings with their own classes (however they have technically implemented it). If you don't do that (and also don't work with tricky and unfortunately also maintenance-requiring selectors like I do), then you leave it to chance whether the conflicts I described with undesirably selected hx elements occur or not. For me, this is simply not a proper system architecture, because headings are regularly formatted (more or less elaborately). And this should be handled systematically and securely, not as shaky and in poor style as I initially implemented it.

Well, I don't really care about it in the end. I just thought I could advance the project with it. The wiki where my case is located is a DokuWiki-on-a-Stick and still runs on Greebo, and I currently have more reasons to stay with it than to upgrade the wiki. Therefore, nothing will change for me in the foreseeable future even if my proposed idea were to be adopted.

\- Michael Sy.

**Comment by Michaelsy** [comment]
Have I understood correctly that the [Actionrenderer plugin](https://www.dokuwiki.org/plugin:actionrenderer) would be a good way to retrofit the class I want via a corresponding plugin (e.g. with the name "Addheadingclass") without replacing the entire HTML renderer?

\- Michael Sy.

**Comment by Klap-in** [comment]
Indeed. However, there are not yet that much other plugins that have implemented support for the actionrenderer plugin.
