### ISSUE TITLE
E_WARNING: Undefined array key "media"

### ISSUE THREAD

**Issue by HMJR** [dokuwiki/dokuwiki#3970]
After upgrading from 2023-04-04 "Jack Jackrum" to 2023-04-04**a** "Jack Jackrum" release these error warnings in the logs occur:

2023-05-17 04:33:58
E_WARNING: Undefined array key "media"
/home//domains//public_html/nl/feed.php(235)
#0 /home//domains//public_html/nl/feed.php(235): dokuwiki\ErrorHandler::errorHandler()
#1 /home//domains//public_html/nl/feed.php(96): rss_buildItems()
#2 {main}
2023-05-17 04:33:58
E_WARNING: Undefined array key "media"
/home//domains//public_html/nl/feed.php(305)
#0 /home//domains//public_html/nl/feed.php(305): dokuwiki\ErrorHandler::errorHandler()
#1 /home//domains//public_html/nl/feed.php(96): rss_buildItems()
#2 {main}

Both PHP version 8.1

**Comment by nerun** [comment]
I got the same erros:
```php
PHP Warning:  Undefined array key "media" in /home/domain/public_html/feed.php on line 235
PHP Warning:  Undefined array key "media" in /home/domain/public_html/feed.php on line 305
```
