### ISSUE TITLE
Fixing PHP 8.2 compatibility for 2 abandoned plugins mediasyntax and WikipediaSnippet - GitHub Sponsor consulting fee as needed

### ISSUE THREAD

**Issue by AzureCloudMonk** [dokuwiki/dokuwiki#3971]
Hi Andy, I was your first or second monthly GitHub Sponsor several years ago and DokuWiki is my favorite software since 2005!

My ISP is forcing me to update from PHP 7.4.15 to 8.1 or 8.2 which causes my most important DokuWiki plugins to fail (mediasyntax by Thorsten Staerk and WikipediaSnippet Plugin by Anika Henke) which then crashes DokuWiki.

In the past 2 years ago when I requested to pay you to update the code of the incompatible https://www.dokuwiki.org/plugin:mediasyntax Mediawiki syntax plugin to work with a newer version of DokuWiki, you kindly did it for free and privately sent me the code files. 

I again would like to offer to pay you consulting fees by increasing my GitHub sponsorship or PayPaling you whatever amount you require to fix the 2 abandoned plugins mediasyntax and WikipediaSnippet.

Would it be possible for you to GitHub fork the 2 abandoned plugins (https://github.com/tstaerk/mediasyntax/issues and https://github.com/selfthinker/dokuwiki_plugin_wikipediasnippet/issues/23 and update them publicly to work with PHP 8.2.0 and Release 2023-04-04a “Jack Jackrum”?  That way others can benefit from the updates.

Thanks again for your greatly useful amazing DokuWiki!

Cloud Monk Losang Jinpa

**Comment by splitbrain** [comment]
This has nothing to do with DokuWiki core so this isn't the right place to discuss this. However I just gave both plugins a quick test and they seem both to run just fine on PHP 8.2. There are a few deprecation warnings in the logs but nothing that needs immediate attention.

**Comment by AzureCloudMonk** [comment]
Hi, When using PHP 8.2 FastCGI or PHP 8.0 FastCGI with a new virgin install of DokuWiki version "2023-04-04a Jack Jackrum" with latest code from https://github.com/tstaerk/mediasyntax (since "Unable to download the file: http://www.staerk.de/files/mediasyntax.tar.gz"), I get the following error:

Error: Attempt to assign property "toplevel_id" on null
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the mediasyntax plugin.

More info has been written to the DokuWiki error log.

If I switch back to using PHP 7.4 FastCGI the problem disappears.

Here is my DokuWiki error log from LogViewer:

2023-05-21 23:24:28

Error: Attempt to assign property "toplevel_id" on null
/home/a7j5do2x9y5qkr8v2k/devopscloud.io/lib/plugins/mediasyntax/action.php(71)
#0 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/Extension/EventHandler.php(80): action_plugin_mediasyntax->handle_parser(Object(dokuwiki\Extension\Event), NULL)
#1 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event(Object(dokuwiki\Extension\Event), 'BEFORE')
#2 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/Extension/Event.php(132): dokuwiki\Extension\Event->advise_before(false)
#3 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger(NULL, false)
#4 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/parser/handler.php(137): dokuwiki\Extension\Event::createAndTrigger('PARSER_HANDLER_...', Object(Doku_Handler))
#5 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/Parsing/Parser.php(123): Doku_Handler->finalize()
#6 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/parserutils.php(234): dokuwiki\Parsing\Parser->parse('\n==Denmark==\n\nR...')
#7 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/parserutils.php(198): p_get_instructions('==Denmark==\n\nRe...')
#8 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/parserutils.php(525): p_cached_instructions('/home/bhikshu_n...', false, 'denmark')
#9 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/parserutils.php(299): p_render_metadata('denmark', Array)
#10 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/inc/common.php(266): p_get_metadata('denmark')
#11 /home/a7j5do2x9y5qkr8v2k/devopscloud.io/doku.php(97): pageinfo()
#12 {main}

**Comment by AzureCloudMonk** [comment]
So, to summarize I will be happy to pay consulting fees to either you Andy or Thorsten Staerk to update the code to solve this problem. Thank you.

**Comment by AzureCloudMonk** [comment]
Weirdly, it seems to  have solved itself by switching back and forth 2 times on my ISP from PHP 8.2 to 7.4 and then back again to 8.2.  Maybe the ISP had some problem with their PHP upgrade process?  It is working OK now. Thanks.
