### ISSUE TITLE
Wrong link to old revs on deleted pages

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki#3980]
At dokuwiki.org refers on a deleted page e.g. https://www.dokuwiki.org/radish_attitude the old revisions link to `https://www.dokuwiki.org/shell.php?do=revisions`. I see it on more removed pages.

**Comment by Klap-in** [comment]
Might be related to #3013

**Comment by fiwswe** [comment]
Actually the link is to `https://www.dokuwiki.org/null?do=revisions` (not `…/shell.php?…` which also seems to be a deleted page you may have confused with `radish_attitude`) which is somewhat strange indeed (the `null` that is).

So in summary:
* https://www.dokuwiki.org/radish_attitude (deleted) -> `https://www.dokuwiki.org/null?do=revisions`
* https://www.dokuwiki.org/shell.php (deleted) -> `https://www.dokuwiki.org/shell.php?do=revisions`

What issue did you mean to raise? The `null` or something else?

**Comment by Klap-in** [comment]
You see that it show up as `null?do=..`, for the link in the text I saw as link`shell.php?do=..`. It should be https://www.dokuwiki.org/radish_attitude?do=revisions

I thinks this is indeed a duplicate of #3013. Probably respectively the cached onceexisted.txt for `shell.php` and `null` page were shown.

**Comment by Klap-in** [comment]
Duplicate of #3013

**Comment by fiwswe** [comment]
> this morning it shows again another link

Ah yes indeed. So the problem seems to be that the link is not only incorrect but also somewhat random. I agree that #3013 may be related.
