### ISSUE TITLE
Install script stops when it doesn’t find language files

### ISSUE THREAD

**Issue by PuppyLord** [dokuwiki/dokuwiki#3990]
When installing dokuwiki and choose to only install a subset of languages.
Then, during an update/grade the installer will stop on an “not writeable file error”. This is due to the fact that non existent files are considered non writable, which makes sense in a way.

A better behavior would be to ignore the write status on files that can not be found, thus allowing upgrades and security patches to be installed on systems that do not have every single language pack installed.

**Comment by fiwswe** [comment]
> the installer

Can you please specify what you mean by this?
Please describe the steps you took to get this issue as well as some things about your environment, e.g. DokuWiki version, OS, PHP version and anything else that may be relevant such as file system permissions. See: [Report a Bug](https://dokuwiki.org/bugs#report_a_bug)

**Comment by PuppyLord** [comment]
Hi.

The system is a synology NAS, but I have installed dokuwiki without the installer built into the NAS operating system. In other words, it is just like any other installation on a linux can.

I  downloaded the dokuwiki version release 2023-04-04 "Jack Jackrum" directly from the dokuwiki site. When I downloaded the file, I elected to only download Swedish and English as the language packs. The installation worked flawlessly in all regards. 

Recently when checking in on the installation I got the message that there were an upgrade available, so I go to “Admin” and then “Wiki Upgrade” and start the procedure. 

All stages works well and in the “Unpack” section this is confirmed by the message “DokuWiki 2023-04-04a "Jack Jackrum" is ready to install (You're currently running Release 2023-04-04 "Jack Jackrum")”.

The next stage, “Verify”, is when things turn sour as I am met with the red failure text stating “Errors above! You should not continue!” (as if I had a choice :) ). Most of the lines are OK but there are some errors. Some of those I had to fix by making the files writeable but some errors can not be addressed as the files do not exists on my system. One such example is “/inc/lang/fi is not writable!” which I can not do anything about since I did not install the Finnish language pack on account of me not speaking the language. 

I went through the entire file listing and most files are given the “will be updated” tag, here’s a list of the lines with error, bear in mind I did not install any of these languages;

/inc/lang/fi is not writable!
/inc/lang/de-informal is not writable!
/inc/lang/gl is not writable!
/inc/lang/is is not writable!
/inc/lang/zh is not writable!
/inc/lang/nan is not writable!
/inc/lang/hu-formal is not writable!
/inc/lang/fy is not writable!
/inc/lang/ko is not writable!
/inc/lang/km is not writable!
/inc/lang/sk is not writable!
/inc/lang/cy is not writable!
/inc/lang/eu is not writable!
/inc/lang/ka is not writable!
/inc/lang/cs is not writable!
/inc/lang/et is not writable!
/inc/lang/hu is not writable!
/inc/lang/af is not writable!
/inc/lang/sl is not writable!
/inc/lang/si is not writable!
/inc/lang/bg is not writable!
/inc/lang/no is not writable!
/inc/lang/zh-tw is not writable!
/inc/lang/mg is not writable!
/inc/lang/nl is not writable!
/inc/lang/ru is not writable!
/inc/lang/kn is not writable!
/inc/lang/fo is not writable!
/inc/lang/ca-valencia is not writable!
/inc/lang/hr is not writable!
/inc/lang/pt-br is not writable!
/inc/lang/it is not writable!
/inc/lang/lt is not writable!
/inc/lang/oc is not writable!
/inc/lang/eo is not writable!
/inc/lang/id-ni is not writable!
/inc/lang/ne is not writable!
/inc/lang/sr is not writable!
/inc/lang/lb is not writable!
/inc/lang/vi is not writable!
/inc/lang/tr is not writable!
/inc/lang/pt is not writable!
/inc/lang/lv is not writable!
/inc/lang/ja is not writable!
/inc/lang/be is not writable!
/inc/lang/mr is not writable!
/inc/lang/pl is not writable!
/inc/lang/id is not writable!
/inc/lang/sq is not writable!
/inc/lang/ckb is not writable!
/inc/lang/ms is not writable!
/inc/lang/la is not writable!
/inc/lang/he is not writable!
/inc/lang/el is not writable!
/inc/lang/hi is not writable!
/inc/lang/de is not writable!
/inc/lang/fr is not writable!
/inc/lang/th is not writable!
/inc/lang/ca is not writable!
/inc/lang/kk is not writable!
/inc/lang/bn is not writable!
/inc/lang/ia is not writable!
/inc/lang/uk is not writable!
/inc/lang/da is not writable!
/inc/lang/ar is not writable!
/inc/lang/mk is not writable!
/inc/lang/ta is not writable!
/inc/lang/fa is not writable!
/inc/lang/hy is not writable!
/inc/lang/ku is not writable!
/inc/lang/az is not writable!
/inc/lang/ml is not writable!
/inc/lang/es is not writable!
/inc/lang/uz is not writable!
/inc/lang/ro is not writable!
/VERSION is not writable!
Some files aren't writable. Automatic upgrade not possible.

I have previously had this error but never reported it, so it shouldn’t be a new thing. Not sure if it is NAS specific, but I cant see why. In any case it should be easy enough to reproduce.

I hope this was clear enough, please let me know if I can get you any more information :)

**Comment by fiwswe** [comment]
> Recently when checking in on the installation I got the message that there were an upgrade available, so I go to “Admin” and then “Wiki Upgrade” and start the procedure.
> 
> All stages works well and in the “Unpack” section this is confirmed by the message “DokuWiki 2023-04-04a "Jack Jackrum" is ready to install (You're currently running Release 2023-04-04 "Jack Jackrum")”.

Are you using the [Upgrade Plugin](https://www.dokuwiki.org/plugin:upgrade)? If so you should probably file the issue there.

**Comment by PuppyLord** [comment]
Yes, I am using that plugin. 
Sorry, I didn't realise it was a different thing since it's part of the package.
Will post there later.

Thanks again for the assist, and sorry for posting in the wrong forum.
