### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by KoreiKhan** [dokuwiki/dokuwiki#4019]
**For some reason I get a 403 error upon try to save the following text on a page:**

`Boot Configuration Database (BCD). `

**Comment by KoreiKhan** [comment]
![image](https://github.com/dokuwiki/dokuwiki/assets/39051012/2a40838f-33bd-48d2-b629-7560bf7dc685)
![image](https://github.com/dokuwiki/dokuwiki/assets/39051012/aebd9499-f0ce-40d8-a7e6-265b54ce0c19)

**Comment by Klap-in** [comment]
As the message notes, the first thing to check is the access to the text files with the content of the pages.
Please check at least the sub folders of `data/` folder for its permissions.

More background can be found in https://www.dokuwiki.org/install:permissions
Further the server error log might have more details.

**Comment by splitbrain** [comment]
https://doku.wiki/mod_security

**Comment by KoreiKhan** [comment]
> https://doku.wiki/mod_security

Thanks for the help! =)


Yeah so it turned out the firewall was blocking access because it might have thought it had malicious code when it in reality, only contained info about databases. 


I put this rule in the .htaccess file of the domain directory of mydokuwiksitename

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{SERVER_PORT} 80
RewriteRule ^(.*)$ https://mydokuwiksitename.com/$1 [R,L]
</IfModule>
