### ISSUE TITLE
Don't replace ".." in inline code

### ISSUE THREAD

**Issue by beatep** [dokuwiki/dokuwiki#4020]
When I enter ''cat text.txt|grep "@" > adressen.txt'' in my page, after saving I have

cat text.txt|grep „@“ > adressen.txt

so the ".." are replaced by the better ones „“, but in this context it is wrong.

**Comment by Klap-in** [comment]
`''"Text"''`applies only a monospaced font, it does not apply the nowiki tags to disable interpretation e.g. `''<nowiki>"Text"</nowiki>''`.

An alternative is the use of [unformatted plugin](https://www.dokuwiki.org/plugin:unformattedcode), which does not these ‘entity’ conversions.

**Comment by fiwswe** [comment]
No plugin needed. Just use the `<nowiki>` or `%%`syntax:
`''%%cat text.txt|grep "@" > adressen.txt%%''`
`''<nowiki>cat text.txt|grep "@" > adressen.txt</nowiki>''`


HTH
fiwswe
