### ISSUE TITLE
Undefined array key "onselect" in C:\Xamp\htdocs\lib\plugins\ckgedit\action\mediamanager.php on line 44 & 46

### ISSUE THREAD

**Issue by Starf0x** [dokuwiki/dokuwiki#4022]
I get that with the opening of the Media Manager.

Version: 2023-04-04a "Jack Jackrum"

**Comment by splitbrain** [comment]
This is ckgedit plugin code. Please report there.

**Comment by fiwswe** [comment]
You should file your issue with the [CKGEdit Plugin](https://dokuwiki.org/plugin:ckgedit).
