### ISSUE TITLE
"require" Deprecation messages in logs after upgrade

### ISSUE THREAD

**Issue by yaynstuff** [dokuwiki/dokuwiki#4026]
Hi,

After upgrading to the latest release, the deprecation log is being spammed with warnings from a number of third party plugins we use (at least half a dozen of them) with messages like:

`2023-08-13 06:54:25             require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/anchor/syntax.php:4 Autoloading should be used instead`

Having to reach out to every plugin author (who are not always responsive) seems like a frustrating process.. How can we fix this deprecation warning in the logs?

I did some googling and found a hit for another docuwiki plugin where a commenter had written that adding the following code in place of the existing 'require' would fix it:

```
   spl_autoload_register(function ($class) {
       require_once(DOKU_PLUGIN.'syntax.php');
   });
```
Some questions on the above code snippet

1) Is it the correct approach?
2) Could it be applied "as is" to any plugin giving this warning?

Thanks!
M.

**Comment by fiwswe** [comment]
> Having to reach out to every plugin author (who are not always responsive) seems like a frustrating process.. How can we fix this deprecation warning in the logs?

Reach out to every plugin author whose plugin generates this warnings ;-) File issues or better yet file PRs.

Or just ignore the warnings (maybe even turn off logging if you feel the logs will up your disk). The real problems will surface when some future release of DW no longer gracefully deals with these issues.

> I did some googling and found a hit for another docuwiki plugin where a commenter had written that adding the following code in place of the existing 'require' would fix it:
> 
> ```
>    spl_autoload_register(function ($class) {
>        require_once(DOKU_PLUGIN.'syntax.php');
>    });
> ```
> 
> Some questions on the above code snippet
> 
> 1. Is it the correct approach?

Maybe check out [General Cleanup Suggestions](https://www.dokuwiki.org/devel:releases:refactor2020#general_cleanup_suggestions)? Seems to me that the `require_once(DOKU_PLUGIN.'syntax.php');` could just be removed. But I have not tested this.
For more general advice see:
* https://www.dokuwiki.org/devel:releases:refactor2022
* https://www.dokuwiki.org/devel:releases:refactor2021
* https://www.dokuwiki.org/devel:releases:refactor2020

In the case of the [Anchor Plugin](https://www.dokuwiki.org/plugin:anchor) I think https://github.com/zioth/dokuwiki-anchor/blob/f55f70712ff4f6a9a566d5507797afb7c33f3fb4/syntax.php#L2-L4 could be removed completely. And while you're at it https://github.com/zioth/dokuwiki-anchor/blob/f55f70712ff4f6a9a566d5507797afb7c33f3fb4/syntax.php#L12-L20 seems redundant as well.
Note: I don't use that plugin so I'll leave the PR as an exercise for you or someone else with a vested interest.

> 2. Could it be applied "as is" to any plugin giving this warning?

I think you'd need to look at each plugin to be sure which solution would be correct.
