### ISSUE TITLE
Warning in info/syntax.php

### ISSUE THREAD

**Issue by Miro-Collas** [dokuwiki/dokuwiki#4033]
PHP 8.1
Dokuwiki Release 2023-04-04a "Jack Jackrum"

```
2023-08-19 07:50:12E_WARNING: Undefined array key "email"/home/fswiki/public_html/lib/plugins/info/syntax.php(150)
    #0 /home/fswiki/public_html/lib/plugins/info/syntax.php(150): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 150)
    #1 /home/fswiki/public_html/lib/plugins/info/syntax.php(81): syntax_plugin_info->renderPlugins('syntax', Object(Doku_Renderer_xhtml))
    #2 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_info->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #3 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('info', Array, 5, '~~INFO:syntaxpl...')
    #4 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #5 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'playground:wiki...')
    #6 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('playground:wiki...', 0, true, '')
    #7 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #8 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #9 [internal function]: tpl_content_core('show')
    #10 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #11 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #12 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #13 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #14 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #15 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #16 {main}
```

**Comment by fiwswe** [comment]
Seems like another case where the API contract is not enforced:
https://github.com/dokuwiki/dokuwiki/blob/0877de155d3e8cab1d6479cab1735cc2acd222ab/inc/Extension/PluginInterface.php#L16:L29

One of your plugins apparently does not have the `email` key in its plugin.info.txt file (or it overrides `getInfo()` incorrectly).

**Comment by Miro-Collas** [comment]
> One of your plugins apparently does not have the `email` key in its plugin.info.txt file (or it overrides `getInfo()` incorrectly).

I wouldn't know where to start looking for that

**Comment by Klap-in** [comment]
Each plugin has a `plugin.info.txt`, one of them might miss the `email` key? The plugins are in /lib/plugins/

**Comment by fiwswe** [comment]
Try this:
`grep -c 'email' /home/fswiki/public_html/lib/plugins/*/plugin.info.txt|egrep ':0$'`

But like I said, some plugin may also override the `getInfo()` method. If such an override does not return the `email` key then that is an error. Find these like this:
`grep -Enr 'function.+getInfo\(' /home/fswiki/public_html/lib/plugins/`
And then check if they always return the right thing.

**Comment by Miro-Collas** [comment]
I'll ask our systadmin to check, thank you. Meantime, what would happen if the line is there, but the email isn't supplied. ie...

```
base    anchor
author  Eli Fenton
email
date    2023-08-14
name    Anchor Plugin
desc    Create an HTML anchor.
url     https://www.dokuwiki.org/plugin:anchor
```

**Comment by fiwswe** [comment]
I think (but did not test) that in the case of an `email` line without a value, the key would be be returned with an empty string or null as the value. I.e. it would not trigger this E_WARNING.

See:
* https://github.com/dokuwiki/dokuwiki/blob/a6f2604a7291850f79101bf119b8170c8970aba8/inc/Extension/PluginTrait.php#L23
* https://github.com/dokuwiki/dokuwiki/blob/a6f2604a7291850f79101bf119b8170c8970aba8/inc/confutils.php#L257
* https://github.com/dokuwiki/dokuwiki/blob/a6f2604a7291850f79101bf119b8170c8970aba8/inc/confutils.php#L218

**Comment by Miro-Collas** [comment]
> Try this: `grep -c 'email' /home/fswiki/public_html/lib/plugins/*/plugin.info.txt|egrep ':0$'`
> 
> But like I said, some plugin may also override the `getInfo()` method. If such an override does not return the `email` key then that is an error. Find these like this: `grep -Enr 'function.+getInfo\(' /home/fswiki/public_html/lib/plugins/` And then check if they always return the right thing.

I asked....

`grep -c 'email' /home/fswiki/public_html/lib/plugins/*/plugin.info.txt|egrep ':0$'`
 Returns nothing. 

`grep -Enr 'function.+getInfo\(' /home/fswiki/public_html/lib/plugins/`
 Returns the following: 
```
/home/fswiki/public_html/lib/plugins/anchor/syntax.php:12:      function getInfo() {
/home/fswiki/public_html/lib/plugins/upgrade/legacy.php:101:    public function getInfo()
```

**Comment by fiwswe** [comment]
The latest version of the [Anchor plugin](https://dokuwiki.org/plugin:anchor) no longer implements the `getInfo()` method. And the older code did not return the `email` key. So you should probably update. This is most likely the root cause of the E_WARNING. See: https://github.com/zioth/dokuwiki-anchor/commit/eabe12dd837380a91ead70e611f8cf17e455ce23

The [Upgrade plugin](https://dokuwiki.org/plugin:upgrade) basically reimplements the default functionality of using plugin.info.txt and that file contains the `email` line.

But you are also correct IMHO that DW should deal better with plugins that don't return the mandatory keys.

**Comment by Miro-Collas** [comment]
> The latest version of the [Anchor plugin](https://dokuwiki.org/plugin:anchor) no longer implements the `getInfo()` method. And the older code did not return the `email` key. So you should probably update. This is most likely the root cause of the E_WARNING. See: [zioth/dokuwiki-anchor@eabe12d](https://github.com/zioth/dokuwiki-anchor/commit/eabe12dd837380a91ead70e611f8cf17e455ce23)

Well, it would be up to the author, I think. I'll open an issue, pointing here.

> But you are also correct IMHO that DW should deal better with plugins that don't return the mandatory keys.

Thanks for confirming that.

**Comment by fiwswe** [comment]
I think you misunderstood. The current version of the [Anchor plugin](https://dokuwiki.org/plugin:anchor) 2023-08-14 already has this issue fixed.

All **you** need to do is update your plugin to this version.

**Comment by Miro-Collas** [comment]
My sincere apologies, I did misunderstand.
