### ISSUE TITLE
Command upgrade not found

### ISSUE THREAD

**Issue by MathieuCJ** [dokuwiki/dokuwiki#4037]
Hi,

I want to upgrade my dokuwiki on Release "Igor", but when I try to upgrade my plugins with 'php bin/plugin.php upgrade check (or run) the reply is "Command upgrade not found".
My php version is 7.4.33 and my plugins are in 5.6.

Have you any ideas ?

**Comment by splitbrain** [comment]
upgrade plugin installed? In any case, not a core issue.

**Comment by MathieuCJ** [comment]
I installed the upgrade plugin, but it require an internet connection to get the recent release (Cannot determine which is the most recent version) . 

In my case, I can't have this connection between my server and the git. 
But I have the Release package on my server. 

Is it possible to do this upgrade without access to the git ?
