### ISSUE TITLE
Duplicates in Japanese Romanization Table

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#4047]
As mentioned in https://github.com/dokuwiki/dokuwiki/pull/4045#discussion_r1310737903 the current Japanese Romanization table contains duplicate keys.

I extracted and sorted all duplicates below (relying on IntelliJ Idea to highlight the duplicates)

```
    'し' => 'shi',
    'し' => 'shi',
    'ち' => 'chi',
    'ち' => 'chi',
    'っし' => 'sshi',
    'っし' => 'sshi',
    'っち' => 'cchi',
    'っち' => 'cchi',
    'っちぇ' => 'cche',
    'っちぇ' => 'cche',
    'っちゃ' => 'ccha',
    'っちゃ' => 'ccha',
    'っちゅ' => 'cchu',
    'っちゅ' => 'cchu',
    'っちょ' => 'ccho',
    'っちょ' => 'ccho',
    'ウィ' => 'whi',
    'ウィ' => 'wi',
    'ウィー' => 'whii',
    'ウィー' => 'wii',
    'ウェ' => 'we',
    'ウェ' => 'whe',
    'ウェー' => 'wee',
    'ウェー' => 'whee',
    'シー' => 'shii',
    'シー' => 'shii',
    'ジー' => 'jii',
    'ジー' => 'jii',
    'チ' => 'chi',
    'チ' => 'chi',
    'チー' => 'chii',
    'チー' => 'chii',
    'ヂィー' => 'dii',
    'ヂィー' => 'dyii',
    'ッシ' => 'sshi',
    'ッシ' => 'sshi',
    'ッシー' => 'sshii',
    'ッシー' => 'sshii',
    'ッチ' => 'cchi',
    'ッチ' => 'cchi',
    'ッチー' => 'cchii',
    'ッチー' => 'chii',
    'ツ' => 'tsu',
    'ツ' => 'tsu',
    'ツー' => 'tsuu',
    'ツー' => 'tsuu',
    'フィ' => 'fi',
    'フィ' => 'fi',
    'フィー' => 'fii',
    'フィー' => 'fyii',
    'フェ' => 'fe',
    'フェ' => 'fe',
    'フェー' => 'fee',
    'フェー' => 'fyee',
    'ヴィ' => 'vi',
    'ヴィ' => 'vyi',
    'ヴィー' => 'vii',
    'ヴィー' => 'vyii',
    'ヴェ' => 've',
    'ヴェ' => 'vye',
    'ヴェー' => 'vee',
    'ヴェー' => 'vyee',
```

If we reduce the list to entries where the same characters have different transliterations we arrive at:

```
    'ウィ' => 'whi',
    'ウィ' => 'wi',
    'ウィー' => 'whii',
    'ウィー' => 'wii',
    'ウェ' => 'we',
    'ウェ' => 'whe',
    'ウェー' => 'wee',
    'ウェー' => 'whee',
    'ヂィー' => 'dii',
    'ヂィー' => 'dyii',
    'ッチー' => 'cchii',
    'ッチー' => 'chii',
    'フィー' => 'fii',
    'フィー' => 'fyii',
    'フェー' => 'fee',
    'フェー' => 'fyee',
    'ヴィ' => 'vi',
    'ヴィ' => 'vyi',
    'ヴィー' => 'vii',
    'ヴィー' => 'vyii',
    'ヴェ' => 've',
    'ヴェ' => 'vye',
    'ヴェー' => 'vee',
    'ヴェー' => 'vyee',
```

When #4045 is merged, all duplicates will be removed from the list. The behaviour will not change, since PHP ignored the duplicates before anyway.

However a Japanes speaker might want to look at the list above and point out which transliteration for the above entries is preferable. In that case the table could be adjusted (needs also adjustments to the tests).

**Comment by ssahara** [comment]
ok, please let me see what I can do something as a Japanese speaker.

**Comment by ssahara** [comment]
Looking #4045,  I found that there are some breaks of _implicit_ sort order for replacement substrings, that 5 vowels set - 'a', 'e', 'i', 'o', 'u'. This will likely not alter the replacement results, but the code will become less maintainable for someone who have enough knowledge of Linguistics.

**Comment by ssahara** [comment]
Here is my idea, but I think most Japanese people will accept them.

    'ウィ' => 'whi',     // rarely  used
    'ウィ' => 'wi',       // preferable
    'ウィー' => 'whii',  //rarely used
    'ウィー' => 'wii',   // preferable
    'ウェ' => 'we',      // preferable
    'ウェ' => 'whe',    // rarely used
    'ウェー' => 'wee',    // preferable
    'ウェー' => 'whee',  // rarely used
    'ヂィー' => 'dii',      // preferable , even rarely used
    'ヂィー' => 'dyii',    // not used
    'ッチー' => 'cchii',  //  less preferable
    'ッチー' => 'chii',   //  preferable
    'フィー' => 'fii',     // preferable
    'フィー' => 'fyii',   // not used
    'フェー' => 'fee',   // preferable
    'フェー' => 'fyee', // not used
    'ヴィ' => 'vi',     // preferable
    'ヴィ' => 'vyi',   // not used
    'ヴィー' => 'vii',   // preferable
    'ヴィー' => 'vyii', // not used
    'ヴェ' => 've',    // preferable
    'ヴェ' => 'vye',  // not used
    'ヴェー' => 'vee',  // preferable
    'ヴェー' => 'vyee',  // not used

**Comment by splitbrain** [comment]
Thanks a lot. After deduplication we already used most of the ones you marked as preferred.

There were only two that I changed based on your feedback.

* `フィー` changed from `fyii` to `fii`
* `フェー` changed from `fyee` to `fee`
