### ISSUE TITLE
Latest SMTP plugin appears not saving auth_pass configuration field

### ISSUE THREAD

**Issue by RJLodigiani** [dokuwiki/dokuwiki#4052]
I have installed the latest version of SMTP.
I configured it because without SMTP mails went to recipients' SPAM folders.
Saving the configuration worked but for the auth_pass field.

**Comment by Michaelsy** [comment]
1. This is the wrong repository here. 
2. If you send your email via the SMTP plugin, this has no influence on whether the email is recognised as SPAM or not.
3. The password is not displayed in the settings for security reasons, 

\- Michael Sy.

**Comment by RJLodigiani** [comment]
Thank you, Michael

A couple of questions?

I did not understand what you meant for " wrong repository here".

I know SMTP does not decide if a message is SPAM or not; as I understand
it, the recipient's browser decides depending on a score the sender's
server creates (a 10/10 score does not go to SPAM). My understanding is the
SMTP plugin stores values the server uses before sending the mail.

 I received from my server's support the values needed.

We strongly recommend you send email SMTP authenticated from your website
using the below SMTP settings:

SMTP hostname: az1-ss44.a2hosting.com
SMTP username: (email account created in cPanel)
SMTP password: (email account password)
SMTP port: 465
authentication enabled.
Encryption: SSL

I suspected the password is not displayed for security reasons (why not use
dots to show there is a password). However, I do not have a way to verify
the password was available.

Testing the connection to SMTP I get:
There was an unexpected problem communicating with SMTP: Unexpected return
code - Expected: 334, Got: 535 | 535 Incorrect authentication data

The log:

Set: the server
Set: the auth
Set: a message will be sent
Connecting to az1-ss44.a2hosting.com at 465
Got: 220-az1-ss44.a2hosting.com ESMTP Exim 4.96 #2 Wed, 06 Sep 2023
11:18:21 -0700
Got: 220-We do not authorize the use of this system to transport unsolicited,
Got: 220 and/or bulk e-mail.
Sent: EHLO [68.66.226.109]
Got: 250-az1-ss44.a2hosting.com Hello az1-ss44.a2hosting.com [68.66.226.109]
Got: 250-SIZE 78643200
Got: 250-8BITMIME
Got: 250-PIPELINING
Got: 250-PIPECONNECT
Got: 250-AUTH PLAIN LOGIN
Got: 250 HELP
Sent: AUTH LOGIN
Got: 334 VXNlcmbWU6
Sent: CQkgIGFkbWluQGhpc3RvcmlhbC1zY291dHM3udGV2aWRlby5vcmc=
Got: 535 Incorrect authentication data

From the log, I see all the values the server needs are there. The only one
I cannot verify is the password.

My hypothesis is that the password is not stored in the SMTP plugin
because I don't see it.

I am getting desperate because I cannot solve the problem. I appreciate any
insight you may have on this issue.

Regards

My site SMTP configuration
[image: image.png]

**Comment by RJLodigiani** [comment]
Ok, thanks for the clarification.
