### ISSUE TITLE
Cannot find START page when login.

### ISSUE THREAD

**Issue by RJLodigiani** [dokuwiki/dokuwiki#4053]
"![image](https://github.com/dokuwiki/dokuwiki/assets/144242336/9d35d632-8a3c-4f9e-9fc2-ac8d29564778)

When clicking [Log In] the start page should appear. Instead I get "This page does not exist anymore".

Screen 'Permission Denied' ok because the site is closed to all.

Email notification with username and password to new user sends URL (2).

Day prior to this behavior:
  - **upgraded Dokuwiki to Jack Jackrum**.
  - **installed plugin HTMLOK**.
  - installed plugin SMTP.
  - deleted plugin SMTP.

Configuration > Basic > start > start

I tried three URL; one works, the other two, not.

** Did I screw up some configuration while upgrading to Jack?**

---

URL (1) [**https://historial-scouts7montevideo.org/DokuWiki/doku.php?id=wikihistorial7o:start**]  > screen Permission Denied

(A)
click Log In (top) > screen Login
click button [Log in] > START OK

(B) 
click button [Log in] > START OK

----

URL (2) [**https://historial-scouts7montevideo.org/DokuWiki**] > screen Permission Denied

(A)
click Log In (top) > screen Login
click button [Log in] > screen START missing 

(B) 
click button [Log in] > screen START missing 

---

URL (3) [**https://historial-scouts7montevideo.org/DokuWiki/doku.php?id=start**] > screen Permission Denied

(A)
click LogIn (top) > screen Login
click button [Log in]  > screen START missing

(B) 
click button [Log in] > screen START missing START

---

**Comment by splitbrain** [comment]
Sorry, usage questions are better suited for the [forum](https://forum.dokuwiki.org). The issue tracker is reserved for bugs and feature requests.

**Comment by RJLodigiani** [comment]
Ok. Undwerstood.
