### ISSUE TITLE
Text with underscore (_) not rendering properly

### ISSUE THREAD

**Issue by hardc0der** [dokuwiki/dokuwiki#4070]
I recently upgraded from 2020-07-29 "Hogfather" to 2023-04-04a "Jack Jackrum" and noticed that something broke with how text with underscores is sometimes rendered. The easiest way I've found to reproduce the problem is an example as below where after the second string with an underscore is added the text renders without the underscore and with either the part before or after the underscore italicized:
```
FOO_UNDERSCORE BAR_UNDERSCORE
```

**Comment by mprins** [comment]
does not reproduce in https://www.dokuwiki.org/sandbox:issue-4070

**Comment by hardc0der** [comment]
Ahh, thanks, it appears to be "Markdowku". I had that installed before upgrading as well but I guess that's what broke.

**Comment by hardc0der** [comment]
Ahh, thanks, it appears to be "Markdowku". I had that installed before upgrading as well but I guess that's what broke.
