### ISSUE TITLE
:.. resolved with warning

### ISSUE THREAD

**Issue by Klap-in** [dokuwiki/dokuwiki#4072]
(For unclear reasons) the indexmenu used `:..` as pointer to the root namespace. This edge case triggers a warning. Not studied further, just report it as eventually there are more edge cases.

```
E_WARNING: Uninitialized string offset -1
/../dokuwiki/dokuwiki/inc/File/PageResolver.php(66)
#0 /../dokuwiki/dokuwiki/inc/File/PageResolver.php(66): dokuwiki\ErrorHandler::errorHandler()
#1 /../dokuwiki/dokuwiki/inc/File/PageResolver.php(36): dokuwiki\File\PageResolver->resolveStartPage()
#2 /../dokuwiki/dokuwiki/lib/plugins/indexmenu/syntax/indexmenu.php(736): dokuwiki\File\PageResolver->resolveId()
#3 /../dokuwiki/dokuwiki/lib/plugins/indexmenu/syntax/indexmenu.php(126): syntax_plugin_indexmenu_indexmenu->parseNs()
etc etc
#17 {main}
```

**Comment by splitbrain** [comment]
I'm trying to add a unit test for this, but I am unsure what our expectations for a `[[:..]]` link would be? It doesn't end in `: ` so technically it shouldn't be the start page? Would it be an empty link and resolve to itself? But that seems counter intuitive to what a user might expect? Basically it comes down to what we expect for any link that ends in `..`

**Comment by splitbrain** [comment]
This test suggests that we ignore trailing `..`:

https://github.com/dokuwiki/dokuwiki/blob/6de7d28d1d24e64f46b171fd38e770430b5af6f2/_test/tests/File/PageResolverTest.php#L53

So for `[[foo:..]]` the result would be `foo`.

But I am still unsure about `[[:..]]`, ignoring would result in the current context page. But the user explicitly wanted the root namespace?

**Comment by Klap-in** [comment]
For the Indexmenu plugin `..` was documented as alternative for `:`, as in that it should give the root ns. (Indexmenu needs a namespace as input). In the code it was converted to `:..`. The comment states it was for backward compatibility to older versions. I guess to older versions of the Indexmenu plugin (as I guess this could not have been Dokuwiki syntax in the past).

The Indexmenu plugin used resolve_id() instead of pageresolve or mediaresolve. 
To prevent random behavior due to the start page resolving, I replaced the logic now with always adding a random page name, which I remove later with getNS().

(Off-topic: Eventually we can also offer a more bare resolver (especially needed by the include plugin, see [issue](https://github.com/dokufreaks/plugin-include/pull/300)))

For me this looks as a quite a corner case, for me both are fine, to solve it as `:` or only fix the warning. As I do not know other cases then this strange use in the Indexmenu. If we have to handle this case in meaningful special manner, other similar cases are then strange as well `:.`, `:~`, `::` etc
