### ISSUE TITLE
Can't access config page after PHP upgrade from 7.2 to 8.29

### ISSUE THREAD

**Issue by heinrich2012** [dokuwiki/dokuwiki#4084]
System environment
Windows 10, IIS, PHP 8.29, Dokuwiki Release 2023-04-04a "Jack Jackrum"

After registering php 8.29 in IIS I cannot access config page in admin section anymore.
I did not find any hint what I should have done to avoid this.

When I set back the php version to 7.2 it works. Any idea ?
Many thanks in advanced

Error message is:
```
TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the config plugin.
```

More info has been written to the DokuWiki error log.

Data from error log:

```
2023-10-11 14:42:30 C:\inetpub\wwwroot\dokuwiki\lib\plugins\config\core\Setting\SettingRenderer.php(23) TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given
#0 C:\inetpub\wwwroot\dokuwiki\lib\plugins\config\core\Setting\SettingRenderer.php(23): method_exists()
#1 C:\inetpub\wwwroot\dokuwiki\lib\plugins\config\core\Configuration.php(170): dokuwiki\plugin\config\core\Setting\SettingRenderer->initialize()
#2 C:\inetpub\wwwroot\dokuwiki\lib\plugins\config\core\Configuration.php(56): dokuwiki\plugin\config\core\Configuration->initSettings()
#3 C:\inetpub\wwwroot\dokuwiki\lib\plugins\config\admin.php(40): dokuwiki\plugin\config\core\Configuration->construct()
#4 C:\inetpub\wwwroot\dokuwiki\inc\Action\Admin.php(33): admin_plugin_config->handle()
#5 C:\inetpub\wwwroot\dokuwiki\inc\ActionRouter.php(83): dokuwiki\Action\Admin->preProcess()
#6 C:\inetpub\wwwroot\dokuwiki\inc\ActionRouter.php(48): dokuwiki\ActionRouter->setupAction()
#7 C:\inetpub\wwwroot\dokuwiki\inc\ActionRouter.php(60): dokuwiki\ActionRouter->construct()
#8 C:\inetpub\wwwroot\dokuwiki\inc\actions.php(16): dokuwiki\ActionRouter::getInstance()
#9 C:\inetpub\wwwroot\dokuwiki\doku.php(126): act_dispatch()
#10 {main}
```

I have deactivated nearly every plugin to see the effect, but still no access.

I also run INFO:rendererplugins from the info plug in and found the "Open document plugin" as a rendererplugin, but deactivation also did not work.

**Comment by splitbrain** [comment]
I think this is caused by something in your config. Could you paste the contents of your `conf/local.php` here? Please be sure to redact any password or otherwise sensitive data.

**Comment by heinrich2012** [comment]
Hi Andi, I have deactivated all nearly all plugins now:

<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: heinrich
 * Date: Tue, 28 Mar 2023 17:03:29 +0300
 */

$conf['title'] = '';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['phpok'] = 1;
$conf['send404'] = 1;
$conf['plugin']['achart']['width'] = '480px';
$conf['plugin']['bpmnioeditor']['treat_as_pages'] = 1;
$conf['plugin']['dw2pdf']['qrcodesize'] = '';

**Comment by heinrich2012** [comment]
<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: heinrich
 * Date: Tue, 28 Mar 2023 17:03:29 +0300
 */

$conf['title'] = '';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['phpok'] = 1;
$conf['send404'] = 1;
$conf['plugin']['achart']['width'] = '480px';
$conf['plugin']['bpmnioeditor']['treat_as_pages'] = 1;
$conf['plugin']['dw2pdf']['qrcodesize'] = '';

**Comment by heinrich2012** [comment]
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: heinrich
 * Date: Tue, 28 Mar 2023 17:03:29 +0300
 */

$conf['title'] = '';
$conf['lang'] = 'de';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['phpok'] = 1;
$conf['send404'] = 1;
$conf['plugin']['achart']['width'] = '480px';
$conf['plugin']['bpmnioeditor']['treat_as_pages'] = 1;
$conf['plugin']['dw2pdf']['qrcodesize'] = '';

**Comment by splitbrain** [comment]
Okay, it's not caused by the config. Can you please check your error log again and see if there's another error logged right before the error you posted? It really seems like there is a renderer plugin that fails to load probably because of an incompatibility with PHP 8. But really only enabled plugins should be loaded at this place... so I am confused how this problem happens for you.

**Comment by Klap-in** [comment]
Jack Jackrum has other line numbers, for me it read as that plugin_load() returns a null for a renderer plugin that is installed. I think that is possible if a plugin is installed but disabled?

from stable branch:
https://github.com/dokuwiki/dokuwiki/blob/871aaf69ac1868037618747e232aa177cf2225d8/lib/plugins/config/core/Setting/SettingRenderer.php#L21-L23

**Comment by splitbrain** [comment]
`plugin_list` should only return enabled plugins by default.

**Comment by Klap-in** [comment]
If the odt plugin is the only renderer plugin, is that plugin up to date in your installation? Could it be that instantiating that plugin breaks (in php8.2) and therefore returns a null.
