### ISSUE TITLE
[snuffleupagus][disabled_function] Aborted execution on call of the function 'include'

### ISSUE THREAD

**Issue by respencer** [dokuwiki/dokuwiki#4089]
Apparently a new PHP security module has been installed on my shared hosting, so now I'm getting this in 2023-04-04a with the arctic theme:

`[16-Oct-2023 16:53:19 UTC] PHP Fatal error:  [snuffleupagus][disabled_function] Aborted execution on call of the function 'include' in ./inc/template.php on line 1715`

https://github.com/dokuwiki/dokuwiki/blob/871aaf69ac1868037618747e232aa177cf2225d8/inc/template.php#L1699-L1717

I'm still investigating, will update if I find any more useful  info.

Reference:

https://snuffleupagus.readthedocs.io/

And the config line that I suspect is responsible:

`sp.disable_function.function("include").value_r("\.(inc|phtml|php)$").allow();`

https://github.com/jvoisin/snuffleupagus/blob/cb3d7aed877ce2a0952c00f1950d57c72d664b49/config/default.rules#L67

**Comment by respencer** [comment]
Okay, it doesn't like:

`./lib/tpl/arctic/footer.html`

This is probably more a template issue than a dokuwiki issue, but I'm putting it here as this is where I suspect most people would look for it or raise another issue about it.

**Comment by Klap-in** [comment]
It only include the file that is requested with file name $file via `tpl_includeFile($file)`, and to find it, it searches on a fixed set of locations.

It is used to read in *.html files which form together your template.

I guess the first thing you could try is to contact your hosting provider about current configuration (for snuffleupagus) and see if the include function can be enabled again.

Otherwise you can see if it can be workaround https://www.dokuwiki.org/tips:disabled_functions

**Comment by respencer** [comment]
@Klap-in:

> It only include the file that is requested with file name $file via `tpl_includeFile($file)`, and to find it, it searches on a fixed set of locations.
> 
> It is used to read in *.html files which form together your template.
> 
> I guess the first thing you could try is to contact your hosting provider about current configuration (for snuffleupagus) and see if the include function can be enabled again.
> 
> Otherwise you can see if it can be workaround https://www.dokuwiki.org/tips:disabled_functions Further, there is not much we can do I think.

Thank you. Include isn't disabled though, it's restricted to only include files ending in `inc`, `phtml`, & `php`.

In my case I could just delete `footer.html`, as I don't need it. Otherwise I could have adjusted the theme and called the file `footer.phtml` or `footer.php` and it would have worked.
