### ISSUE TITLE
Section heading - is always closed with two ==

### ISSUE THREAD

**Issue by saggi-dw** [dokuwiki/dokuwiki#4094]
Each heading can be closed with two = (`===== Header ==`).
Is that right or is something broken?

![2023-10-23_08h16_39](https://github.com/dokuwiki/dokuwiki/assets/64777597/67b0a000-6d0b-4e81-8e1a-8d38e4bd6efe)

**Comment by splitbrain** [comment]
That's intentional and has always been the case. You only need to count the leading equal signs
