### ISSUE TITLE
Redirections after form validation do not rely on X-Forwarded-Host to compute the full URL

### ISSUE THREAD

**Issue by m-martin-78** [dokuwiki/dokuwiki#4103]
Hi,

We have a bit special setup for dokuwiki: at first it was an internal wiki, with an internal URL (https://wiki.internal.example.com), and after a few years we had to open it up on the internet, with a new URL (https://wiki.example.com).

After opening the external URL, we noticed dokuwiki works nicely with both URL except when a redirection occurs after a form submission (login, save page changes, ...), where it uses the internal domain name to build the location URL.

With `phpinfo()`, I have been able to ensure that the external RP sets the `X-Forwarded-Host` correctly and it is correctly received by dokuwiki.

Everything works well when using the internal URL, of course.

Is there a way to make dokuwiki work with both domains?

Thanks!

**Comment by splitbrain** [comment]
The recommended way to run DokuWiki behind a reverse Proxy is to set the baseurl config to the external domain.

**Comment by m-martin-78** [comment]
Yeah, but would it prevent the internal URL to keep working?

**Comment by splitbrain** [comment]
Probably. But why shouldn't your users always use the external url?
