### ISSUE TITLE
Entfernen von doppelten FIXMEs

### ISSUE THREAD

**Issue by Rainbow-Spike** [dokuwiki/dokuwiki#4110]
Ein Stück Code, um ein zweites FIXME aus dem Editor zu entfernen. Platzieren Sie es dort, wo es hingehört
```
let wiki_text = document . querySelector ( '#wiki__text' );
if ( wiki_text && /FIXME/ . test ( wiki_text . value ) ) {
	let trys = wiki_text . value . match ( /FIXME \*\*[^\n]+[\)）]\/\/\n\n/g ); /* Inklusive asiatischer Klammer */
	if ( trys . length > 1 ) wiki_text . value = wiki_text . value . replace ( trys [ 1 ], '' );
}
```

**Comment by Klap-in** [comment]
Please translate it to English. Further, if I understood your description, then I do not understand why you would do this. Please explain why everyone needs this.

**Comment by Rainbow-Spike** [comment]
> Please translate it to English. Further, if I understood your description, then I do not understand why you would do this. Please explain why everyone needs this.
**Removal of duplicate FIXMEs**
A piece of code to remove a second FIXME from the editor. Place it where it belongs

Translated by https://www.deepl.com neural net.

**Comment by Rainbow-Spike** [comment]
If the options copytrans (Copy original language text into the editor when starting a new translation?) and warntrans (Record an incomplete translation warning when copying a translation?) are enabled to insert a FIXME line, and the source translation has not yet been processed, the FIXME line is reinserted into the copied text. And again, and again, if the translators are working independently and have not yet finished their work

**Comment by Rainbow-Spike** [comment]
![изображение](https://github.com/dokuwiki/dokuwiki/assets/3947636/0bd4713a-f417-4fce-a7bb-10c6a5c9b427)
The source language is always taken alphabetically, regardless of the order set in the "translations" option (Space separated list of translation languages (ISO codes)). In the picture, the links to languages are sorted using the CSS tricks with display: flex; and order: <number>
