### ISSUE TITLE
Extension Manager error when plugin API fails in unforeseen way

### ISSUE THREAD

**Issue by Miro-Collas** [dokuwiki/dokuwiki#4135]
Going to Admin -> Extension Manager, I get the following error (from logs):

```
2024-01-07 23:26:57TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given/home/fswiki/public_html/lib/plugins/extension/helper/repository.php(111)
    #0 /home/fswiki/public_html/lib/plugins/extension/helper/extension.php(92): helper_plugin_extension_repository->getData('acl')
    #1 /home/fswiki/public_html/lib/plugins/extension/helper/gui.php(53): helper_plugin_extension_extension->setExtension('acl')
    #2 /home/fswiki/public_html/lib/plugins/extension/admin.php(178): helper_plugin_extension_gui->tabPlugins()
    #3 /home/fswiki/public_html/inc/template.php(188): admin_plugin_extension->html()
    #4 /home/fswiki/public_html/inc/Action/Admin.php(40): tpl_admin()
    #5 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Admin->tplContent()
    #6 [internal function]: tpl_content_core('admin')
    #7 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #8 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #9 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'admin', 'tpl_content_cor...')
    #10 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #11 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #12 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #13 {main}
```

Same with Admin -> Configuration Settings.

Release 2023-04-04a "Jack Jackrum"

Looking at the code, it looks like the line number has changed to 115:

```
               if (count($result)) {
                    $cache->storeCache(serialize($result[0]));
                    return $result[0];
                }
```

I'm not sure why this worked fine until recently. Nothing has been updated recently.

**Comment by ki2377** [comment]
It comes out the same when I log in with the admin account, what's the solution?
![image](https://github.com/dokuwiki/dokuwiki/assets/6487408/10130180-7eda-428c-8ae7-4015b2c321b8)

**Comment by bglopez** [comment]
Looks like the plugin repo API is having issues... just installed a new copy of DokuWiki and was hit with the same message.

URL to api: https://www.dokuwiki.org/lib/plugins/pluginrepo/api.php -- that returns:

Exception: Cannot connect to database
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the pluginrepo plugin.

More info has been written to the DokuWiki error log.

**Comment by Miro-Collas** [comment]
> Looks like the plugin repo API is having issues... just installed a new copy of DokuWiki and was hit with the same message.
> 
> URL to api: https://www.dokuwiki.org/lib/plugins/pluginrepo/api.php -- that returns:
> 
> Exception: Cannot connect to database An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the pluginrepo plugin.
> 
> More info has been written to the DokuWiki error log.

Yep, I just came to the same conclusion. The main website is hosed, currently.

**Comment by fiwswe** [comment]
The data is coming from:
https://github.com/dokuwiki/dokuwiki/blob/cd89aff0a8c3297f0a4ac3b3d63873b9d2393254/lib/plugins/extension/helper/repository.php#L20

And there seems to be a problem on the [dokuwiki.org](https://www.dokuwiki.org) website at the moment.

But that shows that error handling could and probably should be improved here. The unserialised data is not checked and assumed to be an array in line 115 even though it is coming from an external source. And at the moment this assumption is wrong.
https://github.com/dokuwiki/dokuwiki/blob/cd89aff0a8c3297f0a4ac3b3d63873b9d2393254/lib/plugins/extension/helper/repository.php#L112-L122

At the moment this happens:
```
$ curl --url 'https://www.dokuwiki.org/lib/plugins/pluginrepo/api.php?fmt=php&ext[]=blog'
<!DOCTYPE html>
<html>
<head><title>Exception: Cannot connect to database</title></head>
<body style="font-family: Arial, sans-serif">
    <div style="width:60%; margin: auto; background-color: #fcc;
                border: 1px solid #faa; padding: 0.5em 1em;">
        <h1 style="font-size: 120%">Exception: Cannot connect to database</h1>
        <p>An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the pluginrepo plugin.</p>
        <p>More info has been written to the DokuWiki error log.</p>
    </div>
</body>
</html>
$ curl --url 'https://www.dokuwiki.org/lib/plugins/pluginrepo/api.php?fmt=php&ext[]=blog' --head
HTTP/1.1 200 OK
Date: Mon, 08 Jan 2024 01:35:18 GMT
Server: Apache
Vary: Cookie,Accept-Encoding
Set-Cookie: DokuWiki=lgnlca8k2v930l7c3ebrudlidu; path=/; secure; HttpOnly; SameSite=Lax
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: DW7fa065a06cb74b536c124cfbe56ac6d3=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly; SameSite=Lax
Content-Type: text/html; charset=UTF-8

$ 
```
So the URL returns a valid answer (status 200) but the content is a plain HTML error message instead of the expected serialised data. The code _should_ be able to deal with this.
There is even a big fat warning to not pass untrusted data to unserialize [here](https://www.php.net/manual/en/function.unserialize). So we may be dealing with an API design issue here. A simple check for `is_array($result)` might seem like a workaround but there might be more serious potential issues lurking.

Note: The last change to the file was [5 months ago](https://github.com/dokuwiki/dokuwiki/commit/d4f83172d9533c4d84f450fe22ef630816b21d75) so the GitHub repro is newer than the "Jack Jackrum" release version which explains the shift in the line numbers.

**Comment by bglopez** [comment]
For what it's worth I was able to get it report that it couldn't reach the repository server with this change:

```
diff --git a/repository.php b/repository.php.bak
index ca387e6..0bca6c9 100644
--- a/repository.php
+++ b/repository.php.bak
@@ -107,11 +107,7 @@ class helper_plugin_extension_repository extends DokuWiki_Plugin
             $httpclient = new DokuHTTPClient();
             $data = $httpclient->get(self::EXTENSION_REPOSITORY_API.'?fmt=php&ext[]='.urlencode($name));
             if ($data !== false) {
-                //$result = unserialize($data);
                 $result = unserialize($data);
-                if($result === null) {
-                    $this->has_access = false;
-                }
                 if(count($result)) {
                     $cache->storeCache(serialize($result[0]));
                     return $result[0];
```

This was just testing, I wouldn't recommend making this change permanently.

**Comment by fiwswe** [comment]
So how about:
```php
             $data = $httpclient->get(self::EXTENSION_REPOSITORY_API.'?fmt=php&ext[]='.urlencode($name));
             if ($data !== false) {
                 $result = unserialize($data);
                 if(!is_array($result)) {
                     $this->has_access = false;
                 } else if(count($result)) {
                     $cache->storeCache(serialize($result[0]));
                     return $result[0];
```

This does not address the API design issue but it may be a temporary workaround?

**Comment by Miro-Collas** [comment]
I could be wrong, but if the dokuwiki API is down, then I suspect that the Extensions screen will be badly broken even if it doesn't throw an error as it is currently doing).

In other words, if this code isn't getting valid data, it should bail out gracefully with a displayed warning, rather than attemting to continue?

**Comment by fiwswe** [comment]
I have just tested my suggestion. It works fine but a message warning about issues with accessing the DokuWiki plugin repository would improve it even more. Something like this seems to work:
```php
                	$this->has_access = false;
                	msg('Could not access the DokuWiki plugin repository!', -1);
```
(Needs localization of course.)

**Comment by fiwswe** [comment]
There are a few more places in the file where similar code is needed.

**Comment by Miro-Collas** [comment]
The dokuwiki site seems back and extension manager is ... "better". The page loads, then instantly clears:

![dokuwiki_2024-01-08](https://github.com/dokuwiki/dokuwiki/assets/39207573/f0e0c421-f379-4b26-9967-e4a746659f96)

**Comment by Klap-in** [comment]
I expect the connection issues will be solved again now dokuwiki.org is working fine again. Might be that caching of old result causes an empty view?
Of course above issue(s) must be improved.
