### ISSUE TITLE
Attempt to sort Table "DokuWiki Installations" causes error Message

### ISSUE THREAD

**Issue by RainerBielefeld** [dokuwiki/dokuwiki#4152]
### STR:  

1. Visit "[DokuWiki Installations](https://www.dokuwiki.org/dokuinstall)"  
2. Click one of the table headings, for example "Install"  
   »  Expected: New Sort Order  
    Actual: Error Message  😥

### The Error Message  
```
PDOException: SQLSTATE[HY000]: General error: 1 no such column: dwinstallation
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the sqlite plugin.
More info has been written to the DokuWiki error log.
```
![grafik](https://github.com/dokuwiki/dokuwiki/assets/11803749/f1f2b2ee-f360-43d7-9d56-4a235b12d526)

**Comment by fiwswe** [comment]
This is the issue tracker for DokuWiki (the software), not for the [dokuwiki.org](https://dokuwiki.org) website, which confusingly happens to use DokuWiki (the software) 😉

DokuWiki (the software) does not use any SQL database. So the error does not come from DokuWiki (the software). Thus this is the wrong place to report the issue.

However the [dokuwiki.org](https://dokuwiki.org) website may have installed a plugin that does use a database. So the admins of the website will need to figure out what is happening. The [DokuWiki Forum](https://forum.dokuwiki.org/) might be a better place to report problems with the website?

**Comment by splitbrain** [comment]
Its okay to report it here since dokuwiki.org is affected, even though this is indeed a problem in the installed plugins. Most probably the data plugin.
