### ISSUE TITLE
No results when searching media with empty string

### ISSUE THREAD

**Issue by eduardomozart** [dokuwiki/dokuwiki#4154]
I believe the DokuWiki Media Manager (pop-up and standalone) search should return all images when pressing Enter on search box when it's empty instead of "No image was found".
![image](https://github.com/dokuwiki/dokuwiki/assets/2974895/7eeb4e88-0c74-4e70-b850-04bb1f44601a)

**Comment by Jenis07** [comment]
can i contribute on this?

**Comment by eduardomozart** [comment]
> can i contribute on this?

@Jenis07 of course. why not?

**Comment by Jenis07** [comment]
where this issue is located?

**Comment by eduardomozart** [comment]
Hello @Jenis07, I've updated this issue description to include an image of the search box on Media Manager, but I decided to troubleshoot this issue further and I was able to detect the code used to search media and patch it on PR #4171.

**Comment by eduardomozart** [comment]
Hello @Jenis07, I've updated this issue description to include an image of the search box on Media Manager, but I decided to troubleshoot this issue further and I was able to detect the code used to search media and patch it on PR #4171.

**Comment by eduardomozart** [comment]
Hello @Jenis07, I've updated this issue description to include an image of the search box on Media Manager, but I decided to troubleshoot this issue further and I was able to detect the code used to search media and patch it on PR #4171.
