### ISSUE TITLE
Locked Out

### ISSUE THREAD

**Issue by lesw537** [dokuwiki/dokuwiki#4157]
When I save a file I get locked out of my WHOLE web server for an hour with no message other than can't contact server.

I can't find any clues for this. Annoying level 100.

**Comment by fiwswe** [comment]
Hard to tell but that does not sound like a DokuWiki software issue. Try [here](https://www.dokuwiki.org/faq:support) for other options to get help.

Either way, you may want to give more details if you expect anyone to help solve your issue.

**Comment by lesw537** [comment]
Thanks. I'll just switch to software that works.
