### ISSUE TITLE
FEED_DATA_PROCESS event deleted: bug or deprecation?

### ISSUE THREAD

**Issue by gerardnico** [dokuwiki/dokuwiki#4191]
Hallo,

In the last version 2024-02-06 "Kaos", I can see that the event [FEED_DATA_PROCESS](https://www.dokuwiki.org/devel:event:feed_data_process) has been deleted
via this [commit](https://github.com/dokuwiki/dokuwiki/commit/87f6c7185502767dd23d1039195eed23f0048dd1)

Is this a deprecation or is this a bug?

I can't find any information on the [FEED_DATA_PROCESS page](https://www.dokuwiki.org/devel:event:feed_data_process).

Thanks
Nico

**Comment by splitbrain** [comment]
Hmm it was actually dropped in #4156 but rather by accident than by design. I guess this event should be wrapped around this loop?

https://github.com/dokuwiki/dokuwiki/blob/ab86a1cdff274f08d0d99df074557be85357331c/inc/Feed/FeedCreator.php#L53-L55

Can you try and provide a pull request?

**Comment by gerardnico** [comment]
On my laptop, I have the `stable` branch of the Dokuwiki repository. I don't really know if this is a lot of work to switch to the fork and all. I have therefore made the pull request via the GitHub web interface.

It works for me but I have only one test and the event mechanism is still a little bit blurry for me.

I took an example on the FEED_DATA_ADD event to create the event data and of the old code to wrap the loop of items.

Hopefully, that's what you wanted.

All the best
Nico

**Comment by splitbrain** [comment]
Looks okay to me. I was my understanding that you are currently using that event in one of your plugins? Does your plugin work as expected with the changes proposed in your PR?

**Comment by Klap-in** [comment]
Via codesearch this one could be found, https://codesearch.dokuwiki.org/xref/plugin/rssbycreated/action.php#48
Does not look strange, but I did not look in what is in the entries.
