### ISSUE TITLE
After upgrade to Dokuwiki "20240206-Kaos", the "Config" section no longer works

### ISSUE THREAD

**Issue by architectonio** [dokuwiki/dokuwiki#4193]
After upgrading to the latest Dokuwiki "20240206-Kaos", when I try to access the Configuration section, (e.G. https://mywebpage/wiki/start?do=admin&page=config)

I get the follwoing error:

ArgumentCountError: 4 arguments are required, 2 given
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the config plugin.

More info has been written to the DokuWiki error log.

My Server:
- Server: **Debian 12**
- Web: **Apache 2.4.57**
- PHP: **8.2**
- Template: **Bootstrap 3**

**Comment by Klap-in** [comment]
> More info has been written to the DokuWiki error log.

Could you have a look at the error log please and share here the error message(s). Probably you can see it in the Logviewer available via the Admin page, or alternatively via the locations mentioned on this page: 
https://www.dokuwiki.org/faq:blankpage#dokuwiki_error_logs

**Comment by architectonio** [comment]
@Klap-in  Here you go:

2024-02-08 07:40:25
E_WARNING: Undefined array key "htmlok"
/var/www/wiki/lib/plugins/ckgedit/action/meta.php(919)
#0 /var/www/wiki/lib/plugins/ckgedit/action/meta.php(919): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/wiki/inc/Extension/EventHandler.php(80): action_plugin_ckgedit_meta->reset_user_rewrite_check()
#2 /var/www/wiki/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
#3 /var/www/wiki/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
#4 /var/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#5 /var/www/wiki/doku.php(125): dokuwiki\Extension\Event::createAndTrigger()
#6 {main}
2024-02-08 07:40:25
E_WARNING: Trying to access array offset on value of type null
/var/www/wiki/lib/plugins/semantic/helper.php(208)
#0 /var/www/wiki/lib/plugins/semantic/helper.php(208): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/wiki/lib/plugins/semantic/helper.php(298): helper_plugin_semantic->getStructuredData()
#2 /var/www/wiki/lib/plugins/semantic/action.php(143): helper_plugin_semantic->getJsonLD()
#3 /var/www/wiki/inc/Extension/EventHandler.php(80): action_plugin_semantic->json_ld()
#4 /var/www/wiki/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
#5 /var/www/wiki/inc/Extension/Event.php(133): dokuwiki\Extension\Event->advise_before()
#6 /var/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#7 /var/www/wiki/inc/template.php(400): dokuwiki\Extension\Event::createAndTrigger()
#8 /var/www/wiki/lib/tpl/bootstrap3/main.php(32): tpl_metaheaders()
#9 /var/www/wiki/inc/actions.php(30): include('...')
#10 /var/www/wiki/doku.php(131): act_dispatch()
#11 {main}
2024-02-08 07:40:25
E_WARNING: Undefined array key "mail"
/var/www/wiki/lib/plugins/semantic/helper.php(270)
#0 /var/www/wiki/lib/plugins/semantic/helper.php(270): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/wiki/lib/plugins/semantic/helper.php(298): helper_plugin_semantic->getStructuredData()
#2 /var/www/wiki/lib/plugins/semantic/action.php(143): helper_plugin_semantic->getJsonLD()
#3 /var/www/wiki/inc/Extension/EventHandler.php(80): action_plugin_semantic->json_ld()
#4 /var/www/wiki/inc/Extension/Event.php(75): dokuwiki\Extension\EventHandler->process_event()
#5 /var/www/wiki/inc/Extension/Event.php(133): dokuwiki\Extension\Event->advise_before()
#6 /var/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#7 /var/www/wiki/inc/template.php(400): dokuwiki\Extension\Event::createAndTrigger()
#8 /var/www/wiki/lib/tpl/bootstrap3/main.php(32): tpl_metaheaders()
#9 /var/www/wiki/inc/actions.php(30): include('...')
#10 /var/www/wiki/doku.php(131): act_dispatch()
#11 {main}
2024-02-08 07:40:25
E_WARNING: Undefined array key "base"
/var/www/wiki/inc/Extension/PluginController.php(110)
#0 /var/www/wiki/inc/Extension/PluginController.php(110): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/wiki/inc/pluginutils.php(55): dokuwiki\Extension\PluginController->load()
#2 /var/www/wiki/lib/plugins/extension/helper/extension.php(801): plugin_load()
#3 /var/www/wiki/lib/plugins/extension/helper/extension.php(92): helper_plugin_extension_extension->readLocalData()
#4 /var/www/wiki/lib/tpl/bootstrap3/tpl/menu-user.php(47): helper_plugin_extension_extension->setExtension()
#5 /var/www/wiki/lib/tpl/bootstrap3/tpl/navbar.php(193): include_once('...')
#6 /var/www/wiki/lib/tpl/bootstrap3/main.php(51): require_once('...')
#7 /var/www/wiki/inc/actions.php(30): include('...')
#8 /var/www/wiki/doku.php(131): act_dispatch()
#9 {main}

Please let me know if you need the whole log

**Comment by architectonio** [comment]
To avoid any mistake, having a clean log, I renamed the original log file (2024-02-08.log) and recalled the config page again.
Dokuwiki has bviosly created a new one and the content is below.
This is what happens in the log file when I try with **mywikiurl/"start?do=admin&page=config"**


2024-02-08 12:07:14     /var/www/wiki/lib/plugins/ckgedit/action/meta.php(919)  E_WARNING: Undefined array key "htmlok"
  #0 /var/www/wiki/lib/plugins/ckgedit/action/meta.php(919): dokuwiki\ErrorHandler::errorHandler()
  #1 /var/www/wiki/inc/Extension/EventHandler.php(80): action_plugin_ckgedit_meta->reset_user_rewrite_check()
  #2 /var/www/wiki/inc/Extension/Event.php(97): dokuwiki\Extension\EventHandler->process_event()
  #3 /var/www/wiki/inc/Extension/Event.php(137): dokuwiki\Extension\Event->advise_after()
  #4 /var/www/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
  #5 /var/www/wiki/doku.php(125): dokuwiki\Extension\Event::createAndTrigger()
  #6 {main}
2024-02-08 12:07:14     /var/www/wiki/lib/plugins/config/core/Loader.php(216)   E_WARNING: Undefined array key 0
  #0 /var/www/wiki/lib/plugins/config/core/Loader.php(216): dokuwiki\ErrorHandler::errorHandler()
  #1 /var/www/wiki/lib/plugins/config/core/Loader.php(55): dokuwiki\plugin\config\core\Loader->loadExtensionMeta()
  #2 /var/www/wiki/lib/plugins/config/core/Configuration.php(52): dokuwiki\plugin\config\core\Loader->loadMeta()
  #3 /var/www/wiki/lib/plugins/config/admin.php(43): dokuwiki\plugin\config\core\Configuration->__construct()
  #4 /var/www/wiki/inc/Action/Admin.php(35): admin_plugin_config->handle()
  #5 /var/www/wiki/inc/ActionRouter.php(86): dokuwiki\Action\Admin->preProcess()
  #6 /var/www/wiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #7 /var/www/wiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #8 /var/www/wiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #9 /var/www/wiki/doku.php(131): act_dispatch()
  #10 {main}
2024-02-08 12:07:14     /var/www/wiki/inc/Extension/PluginTrait.php(50) E_WARNING: Array to string conversion
  #0 [internal function]: dokuwiki\ErrorHandler::errorHandler()
  #1 /var/www/wiki/inc/Extension/PluginTrait.php(50): sprintf()
  #2 /var/www/wiki/lib/plugins/config/core/Setting/SettingRenderer.php(29): dokuwiki\Extension\Plugin->getInfo()
  #3 /var/www/wiki/lib/plugins/config/core/Configuration.php(180): dokuwiki\plugin\config\core\Setting\SettingRenderer->initialize()
  #4 /var/www/wiki/lib/plugins/config/core/Configuration.php(57): dokuwiki\plugin\config\core\Configuration->initSettings()
  #5 /var/www/wiki/lib/plugins/config/admin.php(43): dokuwiki\plugin\config\core\Configuration->__construct()
  #6 /var/www/wiki/inc/Action/Admin.php(35): admin_plugin_config->handle()
  #7 /var/www/wiki/inc/ActionRouter.php(86): dokuwiki\Action\Admin->preProcess()
  #8 /var/www/wiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #9 /var/www/wiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #10 /var/www/wiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #11 /var/www/wiki/doku.php(131): act_dispatch()
  #12 {main}
2024-02-08 12:07:14     /var/www/wiki/inc/Extension/PluginTrait.php(50) ArgumentCountError: 4 arguments are required, 2 given
  #0 /var/www/wiki/inc/Extension/PluginTrait.php(50): sprintf()
  #1 /var/www/wiki/lib/plugins/config/core/Setting/SettingRenderer.php(29): dokuwiki\Extension\Plugin->getInfo()
  #2 /var/www/wiki/lib/plugins/config/core/Configuration.php(180): dokuwiki\plugin\config\core\Setting\SettingRenderer->initialize()
  #3 /var/www/wiki/lib/plugins/config/core/Configuration.php(57): dokuwiki\plugin\config\core\Configuration->initSettings()
  #4 /var/www/wiki/lib/plugins/config/admin.php(43): dokuwiki\plugin\config\core\Configuration->__construct()
  #5 /var/www/wiki/inc/Action/Admin.php(35): admin_plugin_config->handle()
  #6 /var/www/wiki/inc/ActionRouter.php(86): dokuwiki\Action\Admin->preProcess()
  #7 /var/www/wiki/inc/ActionRouter.php(49): dokuwiki\ActionRouter->setupAction()
  #8 /var/www/wiki/inc/ActionRouter.php(62): dokuwiki\ActionRouter->__construct()
  #9 /var/www/wiki/inc/actions.php(19): dokuwiki\ActionRouter::getInstance()
  #10 /var/www/wiki/doku.php(131): act_dispatch()
  #11 {main}

**Comment by architectonio** [comment]
I can confirm that the patch works
