### ISSUE TITLE
Not enough validation of real name and email of users ("Possibly corruption in your user file")

### ISSUE THREAD

**Issue by zorun** [dokuwiki/dokuwiki#4197]
We get constant errors like this in the error log:

```
User line with less than 5 fields. Possibly corruption in your user file
  [
      "username",
      "$2y$10$XXXXXXXX",
      "realname",
      "",
      ""
  ]
```

The user entries that generate these errors have a `#` in either the Real Name or Email field. It seems to confuse dokuwiki since it stops parsing the rest of the line.

Dokuwiki should definitely do more validation on these fields.

Maybe this has alreay been fixed in Dokuwiki: we run a recent version of Dokuwiki but these users were probably created years ago. Unfortunately I didn't find a way to tell when they were created.

**Comment by splitbrain** [comment]
This has been fixed in #4138

You need to manually fix your users.auth.php by escaping the `#` as `\#`
