### ISSUE TITLE
Bootstrap icons not loading with DokuWiki 2024-02-06 "Kaos"

### ISSUE THREAD

**Issue by esnpolimi** [dokuwiki/dokuwiki#4200]
Navbar icons, and some edit page icons are not loading.
Example error:
"Failed to load /lib/tpl/bootstrap3/iconify.php?prefix=mdi&icons=content-save,arrow-left:1 resource: the server responded with a status of 500 ()"

**Comment by splitbrain** [comment]
please provide actual error data

https://www.dokuwiki.org/faq:error500

**Comment by esnpolimi** [comment]
Hi @splitbrain and thanks for the support!

Here a screen of the problem: no idea why only the last three icons are shown (this from any session of the users authorised to access the edit forms)
![Screenshot 2024-02-09 224358](https://github.com/dokuwiki/dokuwiki/assets/64444747/3c9886a1-b6d2-4234-a954-1b8d1e2baaa0)

Regarding the error, analogous for all other icons, here the full console log:
```
/lib/tpl/bootstrap3/iconify.php?icon=mdi-format-bold.svg:1     
GET https:// ... /lib/tpl/bootstrap3/iconify.php?icon=mdi-format-bold.svg 500 (Internal Server Error)
Image (async)
attr @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
B @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
attr @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
createToolButton @ js.php?t=bootstrap3&tseed=39efbf9b62b8e818d479bc2f220ab6c4:1
(anonymous) @ js.php?t=bootstrap3&tseed=39efbf9b62b8e818d479bc2f220ab6c4:1
each @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
initToolbar @ js.php?t=bootstrap3&tseed=39efbf9b62b8e818d479bc2f220ab6c4:1
(anonymous) @ js.php?t=bootstrap3&tseed=39efbf9b62b8e818d479bc2f220ab6c4:1
e @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
t @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
setTimeout (async)
(anonymous) @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
c @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
fireWith @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
fire @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
c @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
fireWith @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
ready @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
setTimeout (async)
(anonymous) @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
(anonymous) @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
(anonymous) @ jquery.php?tseed=f0349b609f9b91a485af8fd8ecd4aea4:2
/lib/tpl/bootstrap3/iconify.php?icon=mdi-format-italic.svg:1 
```

And here the preview text on the network resource:
```
dokuwiki\Exception\FatalException: Cannot declare class cache because the name is already in use
An unforeseen error has occured. This is most likely a bug somewhere.
More info has been written to the DokuWiki error log.
```

So I found this [case](https://forum.dokuwiki.org/d/16588-solved-how-to-see-debug-log) and it seems debugging has to be enabled (by appending ?do=debug to my URL) in order to check the log file.
However, as I do that, I can't see any update on the ./data/cache/debug.log file on the server, instead a flat page, sent you privately as indicated.

**Comment by splitbrain** [comment]
note to self: related to https://forum.dokuwiki.org/d/22004-problem-bei-installation-kaos

**Comment by splitbrain** [comment]
I can not reproduce the problem with a current release of bootstrap3. The error message suggests that the code tries to redeclare a cache class but I don't see why or where the bootstrap3 template should do such a thing. It is also interesting that the error message says `cache` and not `Cache` or even more correct `dokuwiki\Cache\Cache`.

I think the most likely culprit is some opcache problem (try restarting your apache and/or PHP fpm process) or some left over files (see https://www.dokuwiki.org/install:unused_files).

Also please switch to the dokuwiki template and see if the error remains. If this is is only reproducible with bootstrap3 it is worth to report it to @giterlizzi at the template's issue tracker.

**Comment by esnpolimi** [comment]
Everything working when switching to dokuwiki template!

**Comment by splitbrain** [comment]
Don't bother. I think I found the problem, it's not bootstrap specific per se. A proper fix will come soon.

One more question: what PHP Version are you running?

**Comment by esnpolimi** [comment]
My PHP version is 7.4.33

**Comment by esnpolimi** [comment]
Everything working with bootstrap3 after applying the modifications of your last commit :)
Thanks!

**Comment by rgleason** [comment]
I have this exact same problem.  We are using PHP Version 7.4.33 with Kaos
We are using bootstrap3 also.
Should I make those changes  to inc/cache.php  as well?
https://github.com/dokuwiki/dokuwiki/commit/7a9c51a02e7db6a472b4afebfd75357bd20906fe
