### ISSUE TITLE
Kaos: Many plugins now break the extension list

### ISSUE THREAD

**Issue by zioth** [dokuwiki/dokuwiki#4204]
1. Install any plugin that is either missing "email" (or other field) from plugin.info.txt, or has a blank value. Example: datatemplate
2. Go to the extension list or use ~~INFO:syntaxplugins~~
3. You get an error: "ArgumentCountError: 4 arguments are required, 2 given"
4. The error log doesn't help debug the issue, because there's an error in the log output.

The error is on line 50 of PluginTrait.php. It throws an exception whenever a field is missing. Since extension manager can work without a problem when most these fields are missing, and since email in particular is sometimes excluded for privacy reasons, I suggest not throwing here.

**Comment by Klap-in** [comment]
I assume it is solved by this fix: https://github.com/dokuwiki/dokuwiki/commit/2c978aed5aecf1f9f21a94e0bfa7e66c19141dd1 (for #4193)
