### ISSUE TITLE
syntax error, unexpected '=' in inc/init.php

### ISSUE THREAD

**Issue by clonejo** [dokuwiki/dokuwiki#4206]
```
2024/02/11 11:54:23 [error] 365#365: *342 FastCGI sent in stderr: "PHP message: PHP Parse error:  syntax error, unexpected '=' in /var/www/dokuwiki/inc/init.php on line 462" while reading response header from upstream, client: 47.254.76.138, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.3-fpm.sock:", host: "wiki-intern.aachen.ccc.de"
```

The line was introduced in 3bfb10ae171721a86d76fbfdd122f1d7fd29ce15, #4045 and has been released in [release-2024-02-06](https://github.com/dokuwiki/dokuwiki/releases/tag/release-2024-02-06).

This smells like a newer PHP version is now required. While i probably should update, https://www.dokuwiki.org/requirements#php states that PHP 7.2 is sufficient.

**Comment by splitbrain** [comment]
Ah thanks. Page has been updated. See https://www.dokuwiki.org/changes:

> DokuWiki requires at least PHP 7.4 now

**Comment by clonejo** [comment]
Thanks, that was fast!
