### ISSUE TITLE
Keep getting logged out (Koas)

### ISSUE THREAD

**Issue by McBart** [dokuwiki/dokuwiki#4211]
I updated to KAOS and quickly found out that I have a problem. It keeps logging me out me out when I try to load a page with a image. 

Behaviour for page with image(s)

1. Text on page loads, images don't load 
2.  After refresh I am logged out
3. Pages with only text work, but as soon as I load a page with an image I experience 1. and then 2. 

This is behaviour is specific and repeatable  (Bug in ACL for images?) 

I am logged in as the root user so every should load despite ACL settings

As I need my Wiki on a daily bases I quickly rolled back to JJR. My Wiki works again as expected. 

Let me know what I can do to help troubleshoot this issue. 

Thanks for creating DokuWiki!
Bart

**Comment by splitbrain** [comment]
* any error logs?
* network logs for the page and image requests (from the browser developer console) would help
* a general description of your setup (webserver, php, proxies, etc, config and versions, etc)

**Comment by McBart** [comment]
Hey Andreas, 

As I use my wiki in a daily bases I rolled back the update. 

Would it be helpful if I clone one of my smaller Wiki's upgrade it to Kaos and sent you Wiki- and sever logins (It's on a CloudLinux server with DirctAdmin which also has sFTP and ssh access, you can also choose the PHP version you like to use). This way you are free to analyse the problem and test solutions quick and easy.  (After your done, I just delete the clone). As you know your way around DokuWiki very well, I think this much quicker and saves us both time going back and forward. 

Let me know, Bart

**Comment by splitbrain** [comment]
sure, send login details to andi@splitbrain.org

**Comment by McBart** [comment]
Great! I'll make and test the setup tonight and send you details via mail.

**Comment by McBart** [comment]
This issue is caused by a Safari bug and affects at leats Safari 16.2 - 16.5 and is described in the Apple developers forum https://forums.developer.apple.com/forums/thread/728137
Cookies with setting 'Lax" are affected and keep getting lost, cookies with setting 'None' are not affected. 

With the upgrade from Jack jackrum to Kaos cookie security is tightened and the login cookie is set from 'None' to 'Lax'. Luckily developers have anticipated that this can break tings and introduced a new setting 'samesitecookie' 

Setting 'samesitecookie' to 'blank' or 'none' resolves the issue and I am not logged out anymore in Kaos, when I reload pages with images. 

Note: Setting 'samesitecookie' to 'none' or 'blank' results in a lax security (pun intended)
