### ISSUE TITLE
pagetools In PC mode, the pagetools is partially outweighed viewport  , resulting in an X scrollbar.`

### ISSUE THREAD

**Issue by jbl3010** [dokuwiki/dokuwiki#4212]
### The problem

file lib\tpl\dokuwiki\css\pagetools.less line 30
if tpl____site_width__ = 100%
`right: (-1 * @item-width );// pagetools In PC mode, the viewport is partially outweighed, resulting in an X scrollbar.`
`right: (-1 * @item-width + 4);//Changing the value to +4 or more makes pagetools move left by 4px, which can be solved`

### Version of DokuWiki

2024-02-14a

### PHP Version

8.2

### Webserver and version of webserver

IIS

### Browser and version of browser, operating system running browser

edge 121.0.2277.112

### Additional environment information

none

### Relevant logs and/or error messages

```text
none
```

**Comment by fiwswe** [comment]
* Where does your hypothetical `tpl____site_width__` variable come from? (Or if that is not variable, what is it?) It is not a string found anywhere in the DokuWiki source code.
* What ist "PC mode"?
* What does "the viewport is partially outweighed" mean? (Maybe check a dictionary for the meaning of these words? They don't make any sense in this context. Maybe you were trying to translate word by word from a different language?)
* Of course adding 4 to the value moves the element. What "can be solved" and why?
* There is no DokuWiki version 2024-02-14a. Did you mean 2024-02-06a?

From your description I have absolutely no idea what issue you are seeing.

Does the same thing (whatever it is) happen on [dokuwiki.org](https://dokuwiki.org)?

Does the same thing (whatever it is) happen when you use a different browser?

**Comment by jbl3010** [comment]
![R~8HU}YNKYY7W_3U8`M @M3](https://github.com/dokuwiki/dokuwiki/assets/12623979/f7b78970-e88f-4b2c-8516-2154586f426d)

![4UTPTI$QQ)26IY$~ 917M8S](https://github.com/dokuwiki/dokuwiki/assets/12623979/c74928b8-0e59-4412-a0d7-484ff75967b2)

every site and version if set site width = 100%，can see X scrollbar.

I use machine translation and I'm sorry I can't express what I mean exactly.

**Comment by fiwswe** [comment]
Well in my unmodified installation of DokuWiki 2024-02-06a the `#dokuwiki__site` CSS rule has `max-width: 75em`, not `100%`. The value derives from this setting:
https://github.com/dokuwiki/dokuwiki/blob/3f815ae37e12da597486d9be71a56f305c9b394e/lib/tpl/dokuwiki/style.ini#L83

So you must have made a modification. If that modification then leads to unexpected behavior, then that is not really a DokuWiki issue, is it?

Also that setting is used im multiple places. So if you only modified one of them then you are bound to see strange effects.

Again, does the same issue happen on [dokuwiki.org](https://dokuwiki.org)? If not, your modified copy of DokuWiki is the cause.

BTW: Just for laughs I temporarily modified the `#dokuwiki__site {max-width}` setting to `100%` in the inspector of my Safari 17.3 and there was no horizontal scroll bar. So your browser and possibly things like your fonts may also contribute to the scroll bar being shown. So maybe if you use a value smaller than `100%`, e.g. `99%` or `98%` things might look better in your setup.
