### ISSUE TITLE
After Update to Kaos 2024-02-06a "E_WARNING: Undefined array key "REMOTE_USER"

### ISSUE THREAD

**Issue by rldml** [dokuwiki/dokuwiki#4215]
### The problem

We upgraded to Kaos yesterday. After the upgrade the AD-Plugin don't seem to recognise the Active Directory Groups we are in. The effect is, that we don't see the parts of dokuwiki which are only accessible if your AD-user is in a specified group.

In the error log there is this warning:
```
2024-02-15 15:18:02
E_WARNING: Undefined array key "REMOTE_USER"
/var/www/doc/lib/plugins/authad/adLDAP/adLDAP.php(698)
#0 /var/www/doc/lib/plugins/authad/adLDAP/adLDAP.php(698): dokuwiki\ErrorHandler::errorHandler()
#1 /var/www/doc/lib/plugins/authad/auth.php(171): adLDAP->authenticate()
#2 /var/www/doc/inc/auth.php(284): auth_plugin_authad->checkPass()
#3 /var/www/doc/inc/auth.php(325): auth_login()
#4 /var/www/doc/inc/auth.php(236): auth_login()
#5 [internal function]: auth_login_wrapper()
#6 /var/www/doc/inc/Extension/Event.php(134): call_user_func_array()
#7 /var/www/doc/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
#8 /var/www/doc/inc/auth.php(114): dokuwiki\Extension\Event::createAndTrigger()
#9 /var/www/doc/inc/init.php(238): auth_setup()
#10 /var/www/doc/doku.php(38): require_once('...')
#11 {main}
```

It looks, that dokuwiki cannot connect to an AD-Controller because of a missing key in $_SERVER.

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

8.1.2-1ubuntu2.14

### Webserver and version of webserver

Apache/2.4.52 (Ubuntu)

### Browser and version of browser, operating system running browser

Edge 121.0.2277.112 (64-Bit), Firefox 122.0.1 (64-Bit), Client is Windows 10 22H2 Build 19045.3996, Dokuwiki on Ubuntu 22.04.03 LTS

**Comment by fiwswe** [comment]
The code should probably use the `Server` class ([inc/Input/Server.php](https://github.com/dokuwiki/dokuwiki/blob/master/inc/Input/Server.php)) instead of accessing `$_SERVER` directly. That would avoid these types of exceptions. (No idea if the code would be correct when there is no `$_SERVER['REMOTE_USER']` though.)

Note: I don't have an AD to test so someone else will have to create a PR, sorry.
