### ISSUE TITLE
After Upgrade to Kaos: Failed opening required '/path/to/wiki/lib/plugins/authad/adLDAP/adLDAP.php

### ISSUE THREAD

**Issue by jowodo** [dokuwiki/dokuwiki#4216]
### The problem

Following [this guide](https://www.dokuwiki.org/install:upgrade) on manual upgrade from previous version 2023-04-04a "Jack Jackrum". After step 4 (copying of extracted files to `/path/to/wiki/` I wanted to check if any plugins could be updated. At this moment I am still logged in and navigate to `Admin>Extension Manager`, but no plugins are shown and I get this error: 
```
dokuwiki\Exception\FatalException: require_once(): Failed opening required '/path/to/wiki/lib/plugins/authad/adLDAP/adLDAP.php' (include_path='.:/usr/share/awl/inc')
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the authad plugin.

More info has been written to the DokuWiki error log.
```

After successfully logging out and in again I got the same error in the Extension Manager. 
I tried to move the folder `/path/to/wiki/lib/plugins/authad` somewhere else. After reloading the Extension Manager page some plugins are shown for under 1 second and then no plugins and no error is shown at installed plugins tab. 

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

PHP 7.4.3-4ubuntu2.19

### Webserver and version of webserver

2.4.41-4ubuntu3.15

### Browser and version of browser, operating system running browser

Brave 1.62.165 Chromium: 121.0.6167.184 (Official Build) (arm64) on macOS 13.5.2

### Relevant logs and/or error messages

```text
2024-02-17 20:03:38     /path/to/wiki/lib/plugins/authad/auth.php(82)       E_WARNING: require_once(/path/to/wiki/lib/plugins/authad/adLDAP/adLDAP.php): failed to open stream: No such file or directory
  #0 /path/to/wiki/lib/plugins/authad/auth.php(82): dokuwiki\ErrorHandler::errorHandler()
  #1 /path/to/wiki/lib/plugins/authad/auth.php(82): require_once()
  #2 /path/to/wiki/inc/Extension/PluginController.php(130): auth_plugin_authad->__construct()
  #3 /path/to/wiki/inc/pluginutils.php(55): dokuwiki\Extension\PluginController->load()
  #4 /path/to/wiki/lib/plugins/extension/helper/extension.php(801): plugin_load()
  #5 /path/to/wiki/lib/plugins/extension/helper/extension.php(92): helper_plugin_extension_extension->readLocalData()
  #6 /path/to/wiki/lib/plugins/extension/helper/gui.php(55): helper_plugin_extension_extension->setExtension()
  #7 /path/to/wiki/lib/plugins/extension/admin.php(181): helper_plugin_extension_gui->tabPlugins()
  #8 /path/to/wiki/inc/template.php(205): admin_plugin_extension->html()
  #9 /path/to/wiki/inc/Action/Admin.php(43): tpl_admin()
  #10 /path/to/wiki/inc/template.php(120): dokuwiki\Action\Admin->tplContent()
  #11 [internal function]: tpl_content_core()
  #12 /path/to/wiki/inc/Extension/Event.php(134): call_user_func_array()
  #13 /path/to/wiki/inc/Extension/Event.php(200): dokuwiki\Extension\Event->trigger()
  #14 /path/to/wiki/inc/template.php(102): dokuwiki\Extension\Event::createAndTrigger()
  #15 /path/to/wiki/lib/tpl/dokuwiki/main.php(60): tpl_content()
  #16 /path/to/wiki/inc/actions.php(30): include('/var/www/capowi...')
  #17 /path/to/wiki/doku.php(131): act_dispatch()
  #18 {main}
2024-02-17 20:03:38     /path/to/wiki/lib/plugins/authad/auth.php(82)       E_COMPILE_ERROR: require_once(): Failed opening required '/path/to/wiki/lib/plugins/authad/adLDAP/adLDAP.php' (include_path='.:/usr/share/awl/inc')
  #0 [internal function]: dokuwiki\ErrorHandler::fatalShutdown()
  #1 {main}
```
```

**Comment by jowodo** [comment]
After restoring the backup I get the same behavior like after moving the `/path/to/wiki/lib/plugins/authad` folder: The plugins show for under a second and vanish afterwards. 
I tried in a different Browser (Safari) and it worked as expected (all installed plugins are shown). 

So, I installed the [DokuWiki Upgrade Plugin](http://www.dokuwiki.org/plugin:upgrade) and the upgrade worked without a problem. 

I also disabled and uninstalled ADauth plugin after the upgrade since I don't need it

**Comment by jowodo** [comment]
installed plugins are correctly shown in brave (private mode) in Jack Jackrum

**Comment by jowodo** [comment]
The checkboxes `enabled`, `disabled` and `updatable` were not ticked. That's why the plugins where not shown 😅

**Comment by fiwswe** [comment]
The unchecked checkboxes do not explain the PHP exception you cited.

I assume that the file `…/lib/plugins/authad/adLDAP/adLDAP.php` does in fact exist? If so, I'd verify that the access rights are set so that the web server / PHP process can at least read all of the files. Depending on your setup the web server / PHP may run as user `www`, `_www`, `www-data` or something similar. (I don't have an Ubuntu to test and you did not specify which web server software you are using, nor whether you are using PHP-FPM or something else, such as mod_php.)

BTW: The version number seems to indicate that you may be using a very old version of Apache httpd. And PHP 7.4.3 is also old and out of support. I am pretty sure that much more current versions are available on Ubuntu. So you may want to think about updating to newer versions of both.

**Comment by jowodo** [comment]
The file `…/lib/plugins/authad/adLDAP/adLDAP.php` does not exist.
Active Directory Auth Plugin was disabled (not uninstalled) before upgrading.

**Comment by fiwswe** [comment]
>The file `…/lib/plugins/authad/adLDAP/adLDAP.php` does not exist.

Then your install or upgrade went wrong. That file is a part of the standard DokuWiki installation.

>Active Directory Auth Plugin was disabled (not uninstalled) before upgrading.

That should not make any difference.
