### ISSUE TITLE
Page access control issue

### ISSUE THREAD

**Issue by permaBox** [dokuwiki/dokuwiki#4243]
### The problem

My wiki pages as well as e.g. https://www.dokuwiki.org/extensions shows the edit button and can be changed without assigned rights!
BTW, the captcha can be misinterpreted easily. It shows spaces between the letters e.g. K L M ... but KLM ... without spaces is expected!?

### Version of DokuWiki

latest

### PHP Version

7.4

### Webserver and version of webserver

Apache 2.4

### Browser and version of browser, operating system running browser

W10/11 FF/Brave

**Comment by splitbrain** [comment]
dokuwiki.org is mostly publicly editable by design. If your wiki is editable even though you don't want that you have set up your ACLs wrong or did not even enable them (maybe you didn't run the installer?)

**Comment by permaBox** [comment]
ACL permission is correctly set on only "all read". I use DokuWiki for about 15 years ... 
The issue popped up only with the last version and the ACL setting was not changed.

**Comment by fiwswe** [comment]
I can **not** reproduce this on a public (visibility), private (editability) wiki. Nothing can be edited when not logged in.

* DokuWiki Release 2024-02-06a "Kaos" (upgraded from "Jack Jackrum" without changing ACLs)
* PHP 8.3.3
* ACLs are set to `Read` for `@ALL`, `None` for namespace `playground` and full rights for certain groups, users and namespaces.
* [useacl](https://www.dokuwiki.org/config:useacl) is set to **on** (checked).

@permaBox You'll need to provide more information if you feel this is bug somewhere.
