### ISSUE TITLE
Portrait Images not displaying

### ISSUE THREAD

**Issue by POpus** [dokuwiki/dokuwiki#4250]
### The problem

I just moved my Wiki to a new server and noticed that imported images that are in portrait mode from my phone are not displayed.  Tried importing a new file to rule out moving the data was the issue, and same result; landscape OK, portrait broken.

Tried both Vivaldi and Firefox

Error from log:
2024-03-28 20:47:54	/var/www/cabwiki/vendor/splitbrain/slika/src/GdAdapter.php(96)	ArgumentCountError: imagerotate() expects exactly 3 arguments, 4 given
  #0 /var/www/cabwiki/vendor/splitbrain/slika/src/GdAdapter.php(96): imagerotate()
  #1 /var/www/cabwiki/vendor/splitbrain/slika/src/GdAdapter.php(69): splitbrain\slika\GdAdapter->rotate()
  #2 /var/www/cabwiki/inc/media.php(1799): splitbrain\slika\GdAdapter->autorotate()
  #3 /var/www/cabwiki/inc/media.php(1841): media_mod_image()
  #4 /var/www/cabwiki/lib/exe/fetch.php(102): media_crop_image()
  #5 {main}

My PHP version on the new server is 8.3.4 , old is 8.0.30

Found this in the PHP:imagerotate documentation:
**8.3.0	The unused ignore_transparent has been completely removed.**

Must be the problem....

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

8.3.0

### Webserver and version of webserver

Apache 2.4 on Ubuntu Server 

### Browser and version of browser, operating system running browser

Vivaldi/Firefox on LinuxMint

**Comment by mprins** [comment]
please report to Slika at https://github.com/splitbrain/slika/issues preferably with a sample image for a testcase
