### ISSUE TITLE
New line in text should be rendered as such and not appended to the line

### ISSUE THREAD

**Issue by D267-dev** [dokuwiki/dokuwiki#4259]
In draft view
"line1
line2"
is rendered as
"line1 line2" in normal view.

Only 
"line1

line 2"
is rendered in normal view as it is displayed in the draft view.

**Comment by D267-dev** [comment]
Hi splitbrain,
is this a easy problem suitable as a first issue?
If so where could I start?
Would my fix be accepted?
Greetings

**Comment by Klap-in** [comment]
DokuWiki only renders whitelines if you used an empty white line. A single newline is absorbed, a double newline not. The idea is that a whiteline improves also the readability of the raw wiki text in the editor, while editors has not to bother too much about difficult to spot newlines. If you need an explicit newline, see https://www.dokuwiki.org/wiki:syntax#basic_text_formatting
