### ISSUE TITLE
RFC: Official Docker Image

### ISSUE THREAD

**Issue by splitbrain** [dokuwiki/dokuwiki#4261]
This is a follow up to #1896 and #3381.

My attempt in #3381 is IMO the most elegant solution. However the requirement of elevated permissions to be able to use an overlay file system makes this solution impractical for real world usage.

At @cosmocode we have been relying on the Bitnami image  for a while to deploy DokuWiki instances in our Kubernetes cluster. However I am not super happy with that image. We encountered problems mostly when updating containers to new DokuWiki versions: with core plugins being stale (because they had been copied into the volume) and with Bitnami internal changes that were not correctly migrated on container renewal...

In an attempt to create an image we can use instead, I came up with https://github.com/cosmocode/docker-dokuwiki

My goals were:

* a simple image based on a stable base image (the official PHP apache image)
* proper persistance for all user generated/modified content (including plugins, templates and configuration)
* update safe: upgrading DokuWiki means simply updating the container, reusing the existing volume

The container should not:

* run multiple processes
* use any complicated process management
* handle SSL
* handle mail sending

All these things are better handled by properly composing multiple containers. 

:question:  First of all I would like to get comments on the container setup. I'm sure there are things that would be worth improving.

:question: Secondly, I wonder if it would be worth it to promote this setup to "official" status, by moving the repo to the @dokuwiki org and to auto build and publish the image on Docker hub.

**Comment by vbrozik** [comment]
That is great that there will be an official Docker image!

I am using this compose file with DokuWiki installed in a volume:
https://github.com/vbrozik/docker-containers/tree/main/dokuwiki
The main function the compose file provides is setup/restore from a backup archive and making a backup.

What do you think about including compose file(s) into your repository? For normal users it is difficult to take care of backups in the Docker environment. I think it would be really useful to include the backup functionality in the official repository. Of course anything from my repository can be used.

Regarding your Docker Image:

* I think it would be useful to include a parameter for installing a specific DokuWiki version but I do not know how it is normally done in Docker image setups.
* What would happen if you run the [Upgrade](https://www.dokuwiki.org/plugin:upgrade) plugin from the docker image? If it can break something there should probably be some kind of protection.

**Comment by splitbrain** [comment]
* there is already a docker-compose file in the repo: https://github.com/cosmocode/docker-dokuwiki/blob/main/docker-compose.yml
* the upgrade plugin is permanently disabled in the image: https://github.com/cosmocode/docker-dokuwiki/blob/main/root/var/www/html/conf/plugins.docker.php
* for different DokuWiki versions, different docker tags should be used. I will look into automating that

**Comment by splitbrain** [comment]
Update: the repository has been moved to the dokuwiki organization and first images have been published to docker hub.

Please report any issues you might encounter at the docker repo: https://github.com/dokuwiki/docker/issues
