### ISSUE TITLE
DokuWiki can't be opened

### ISSUE THREAD

**Issue by pelayojove** [dokuwiki/dokuwiki#4264]
### The problem

My DokuWiki cant be initiated in any way due to a "Vote Plugin" bug.

The page literally says:

"dokuwiki\Exception\FatalException: Declaration of syntax_plugin_vote::handle($match, $state, $pos, &$handler) must be compatible with dokuwiki\Extension\SyntaxPlugin::handle($match, $state, $pos, Doku_Handler $handler)
An unforeseen error has occured. This is most likely a bug somewhere. It might be a problem in the vote plugin.

More info has been written to the DokuWiki error log."

Thx.

### Version of DokuWiki

2024-02-14a Kaos

### PHP Version

8.3

**Comment by splitbrain** [comment]
uninstall the vote plugin then.

**Comment by pelayojove** [comment]
How can i do that if I cant get into the wiki? Sorry, that was that i was asking for

**Comment by splitbrain** [comment]
Sorry, usage questions are better suited for the [forum](https://forum.dokuwiki.org). The issue tracker is reserved for bugs and feature requests.
