### ISSUE TITLE
`firstimage` does not return correct values for images other than PNGs, JPEGs or GIFs

### ISSUE THREAD

**Issue by sludgeFudge** [dokuwiki/dokuwiki#4269]
### The problem

Hi there,  a huge thank you to the dokuwiki team for making a fabulous piece of software. Now to the issue at hand.

The [nspages](https://www.dokuwiki.org/plugin:nspages) plugin has a feature that allows for listing all the pages in a namespace and displays their first image ([Example](https://www.dokuwiki.org/plugin:nspages#pictures)).
This works well if the images are PNGs, JPEGs, or GIFs but not for JPEG XL, WEBP and AVIF. In the later group's case, what is displayed instead is the default dokuwiki logo.

I have already reported this as a bug on the nspages Issues page: [ "nspages -usePictures" only supports JPEG and PNG #162](https://github.com/gturri/nspages/issues/162). 
There I have provided screenshot examples as well and the maintainer has told me that this feature depends on dokuwiki returning a valid `firstimage` metadata property.  

----

To paraphrase the maintainer's findings:

>I think it probably has to do with what dokuwiki considers to be the "first image" of a page. In the sense that what nspages does is just
>```
>$meta = p_get_metadata($pageId);
>$picture = $meta['relation']['firstimage'];
>```
>(snippet from https://github.com/gturri/nspages/blob/master/printers/printerPictures.php#L49 )
>so I guess Dokuwiki metadata doesn't return a "first image" for that page.

>I made a test. I tried with 3 pages:
> *   one with a png
> *  one without images at all
> *  one with a jxl

He observed that the PNG page would have it's image displayed but the other two would have the default dokuwiki logo instead. 

>now, when I look into the "meta" files for those pages (ie: when I look into the files data/meta/<my-namespace>/<my-page>.meta, what I observe is:
> * the meta file for the page with the png contains `"firstimage";s:19:"playground:test.png"`, which is expected)
> * for the page with no image, it does not contain any `firstimage` key, which makes sense
> * for the page with the jxl, it contains `"firstimage";s:0:"";, which is incorrect

>This confirms the intuition that the issue is on Dokuwiki side (which fails to fill firstimage when we use an exotic format

>As long as this meta "firstimage" key is not correctly filled by Dokuwiki, there is no chance that nspages can display it correctly (and also, I guess that nspages should work as expected as soon as Dokuwiki behavior is fixed).

### Version of DokuWiki

2023-04-04a “Jack Jackrum”

### PHP Version

8.2.18

### Webserver and version of webserver

Apache 2.4.58 on Fedora Linux 39

### Browser and version of browser, operating system running browser

Waterfox/Firefox

**Comment by mprins** [comment]
what happens in a current release?  webp was added as a supported mime type a while ago and should work in the current release looking at https://github.com/dokuwiki/dokuwiki/blob/31afae8a5238b24d15fc0e6f342ee8341d1014dd/inc/parser/metadata.php#L744-L746

jpegxl and avif seem a little exotic imo, the former not even supported by the major browser vendors

**Comment by sludgeFudge** [comment]
Not sure, I'll have to manually switch from the fedora package supplying dokuwiki as it seems to have lost its maintainer. Would manually editing the metadata.php file in my installation break future updates?

I'll agree about the exotic formats but I don't think there'll be an issue in adding them to the if statement. Will there really be an issue? Dokuwiki happily displays the images in the page itself.

**Comment by sludgeFudge** [comment]
I've configured the line to:
```
        if (preg_match('/.(jpe?g|gif|png|webp|svg|jxl|avif)$/i', $src)) {
            $this->firstimage = $src;
        }
```
And it works wonderfully. Would it be problematic to have this in the official dokuwiki code?
