### ISSUE TITLE
align url for lib/plugin members

### ISSUE THREAD

**Issue by Zweihorn** [dokuwiki/dokuwiki#4270]
### The problem

Provide standard url prefix to `plugin.info.txt` for lib/plugin members
ref [standard URL prefix for plug-ins](https://forum.dokuwiki.org/d/22212-standard-url-prefix-for-plug-ins)

The below information seems to be irrelevant to this issue.

### Version of DokuWiki

2024-02-06a "Kaos" [55.1]

### PHP Version

8.2.18

### Webserver and version of webserver

Apache 2.4.59 on Debian GNU/Linux 12.5 Bookworm

**Comment by Zweihorn** [comment]
Please note I will seek to combine the next commits into one PR in due time.

**Comment by Zweihorn** [comment]
Please be aware these minor changes made the respective code segments produce several warnings in the GitHub automatic checks.

This includes, but is not limited to, some **PHP deprecated** warnings as:
  * `Warning: .PHP Deprecated:  Function strftime() is deprecated`
  * `Warning: ........PHP Deprecated:  Function utf8_encode() is deprecated`

mainly in _PHP 8.x checks_ like:
  * [PHP 8.1](https://github.com/dokuwiki/dokuwiki/actions/runs/8902078205/job/24447283146?pr=4274)
  * [PHP 8.2](https://github.com/dokuwiki/dokuwiki/actions/runs/8902078205/job/24447283318?pr=4274)
  * [PHP 8.3](https://github.com/dokuwiki/dokuwiki/actions/runs/8902078205/job/24447283517?pr=4274)


However, I am not the expert here and could agree with [michaelsy](https://forum.dokuwiki.org/d/22212-standard-url-prefix-for-plug-ins/2) in

> that many other corners are in more urgent need of cleaning

Keep on the good work and prosper.

🌻

**Comment by fiwswe** [comment]
The warnings aren't the problem. The errors are. E.g.:
https://github.com/dokuwiki/dokuwiki/actions/runs/8902078205/job/24447283517#step:7:185

**Comment by Zweihorn** [comment]
> The warnings aren't the problem. The errors are. E.g.: https://github.com/dokuwiki/dokuwiki/actions/runs/8902078205/job/24447283517#step:7:185

THX - I was aware of that but only by your comment and helpful hint I got motivated to continue my efforts.

**Comment by Zweihorn** [comment]
Voila. Apparently, my tinkering was worth the effort and just one failed check remains.

  * [Windows Unit Tests / PHP 8.2](https://github.com/dokuwiki/dokuwiki/actions/runs/8908336184/job/24463768011?pr=4274)

All other ten checks were successful now.

**Comment by fiwswe** [comment]
The actual error is here:
https://github.com/dokuwiki/dokuwiki/actions/runs/8908336184/job/24463768011?pr=4274#step:6:47

And it is one of the weird timestamp errors that pop up occasionally in the automated tests. The root cause is almost certainly unrelated to your changes (though I don't fully understand the causes of these errors). Sometimes there are off-by-one-second errors, in this case it was off-by-one-hour-and-one-second. Running the test again might work without errors or with different ones. So you can just ignore this type of error in this PR.

**Comment by Zweihorn** [comment]
More tinkering seems to be pointless to me as I reached some background process.
```
Error:  2024-05-01 10:38:08	C:/Users/RUNNER~1/AppData/Local/Temp/dwtests-1714559855.0139/data/pages/page4.txt	Warning: current file modification time is older than last revision date
  File revision: 1714556288 2024-05-01 09:38:08
  Last revision: 1714559887 2024-05-01 10:38:07
```
ref https://github.com/dokuwiki/dokuwiki/actions/runs/8908336184/job/24463768011?pr=4274#step:6:47

My multi-file search over the dokuwiki code base provides no hits apparently:
![Bildschirmfoto 2024-05-01 um 12 57 24](https://github.com/dokuwiki/dokuwiki/assets/4863737/b69238fd-92fa-4d67-808a-90e2600e0582)

However, I now see that @fiwswe again provided again some helpful insights.

THX - So I can just **ignore this type of error** in this PR.

Voila.

Hope this helps.
🌻

**Comment by fiwswe** [comment]
`…/data/pages/page4.txt` is not a part of DokuWiki. It is a test file generated for the automated tests when they are run. Hence the location in the the `Temp` directory.

See: https://github.com/dokuwiki/dokuwiki/blob/31afae8a5238b24d15fc0e6f342ee8341d1014dd/_test/tests/inc/common_saveWikiText.test.php#L486-L488

So your multi-file search was bound to fail.

**Comment by Zweihorn** [comment]
> So your multi-file search was bound to fail.

This was understood in advance by me. Sometimes I might appear a little chatty and I tend to document my steps even if all seems clear to me just for sharing the experience. However, thanks again for the helpful insights.

This makes my tinkering even more worth to me as a good learning experience.

**Comment by Zweihorn** [comment]
THX @fiwswe and andi approved this.

Voila.
🌻
