### ISSUE TITLE
Edit meta data in Media Manager changes file access mode

### ISSUE THREAD

**Issue by Ragos81** [dokuwiki/dokuwiki#4296]
### The problem

When using the Media Manager to change the meta data of a picture, changes also the access mode of the picture (from 0777 to 0600).

Before the change:
![image](https://github.com/dokuwiki/dokuwiki/assets/55839975/390992e5-a007-415b-9494-a9dad50e7068)
![image](https://github.com/dokuwiki/dokuwiki/assets/55839975/c4d8298f-d46c-4d2d-a2b4-7d01e1443aa7)

After the change:
![image](https://github.com/dokuwiki/dokuwiki/assets/55839975/32aa7b07-e740-4a6a-b21a-d4e5d8f1f698)
![image](https://github.com/dokuwiki/dokuwiki/assets/55839975/f89b5a24-533d-4970-a75e-552074302cbb)

The changed attributes cause issues when exporting the pictures via sftp as the sftp user has no access to this picture anymore.

### Version of DokuWiki

2024-02-06a "Kaos"

### PHP Version

8.2.7

### Webserver and version of webserver

Apache/2.4.57 (Debian)

### Browser and version of browser, operating system running browser

Edge 126.0.2592.68 on Windows 10

### Additional environment information

madiarevisions = enabled
gdlib = Autodetection
im_convert = 
jpg_quality = 70
fetchsize = 0
refcheck = true

**Comment by mprins** [comment]
what is your [fmode](https://www.dokuwiki.org/config:fmode) setting?

**Comment by Ragos81** [comment]
@mprins 
Sorry for the late reply, I was on vacation and totally forgot about it a when I came back.

You was absolutely right, the **fmode** was set to **0644**, now I changed it to **0775** and everything works as it should.

Thanks a lot!
