### ISSUE TITLE
Incorrect pointer to wrong plugin address and duplication of plugin entry

### ISSUE THREAD

**Issue by stroggprog** [dokuwiki/dokuwiki#4302]
### The problem

I was trawling through the extension manager to see if any of my installed plugins needed updating, and saw that one of my own unexpectedly did. It stated the repo address had changed, but it hadn't. On a backup copy of my wiki I installed the plugin and got an error. When I scrolled down to the extension again, I saw there were two entries for my plugin, one pointed at my own repository, and the other pointed at a repo which hasn't been updated in 12 years.
![toucher2](https://github.com/user-attachments/assets/6949cd9e-e8ff-467c-98fc-e127e839575c)
I have checked the plugin pages for both 'toucher2' and 'toucher' and everything seems to be in order. I uninstalled both versions, then searched for and installed 'toucher2'. After installation, everything is ok. Since the resolution was as simple a an uninstall followed by re-install, this report should have a low priority, however, it is odd enough I thought it should be brought to your attention. My biggest concern was that it stated the repo had been updated to the the 12yr old version of the plugin.

### Version of DokuWiki

"Kaos"

### PHP Version

8.3

### Webserver and version of webserver

Apache

### Browser and version of browser, operating system running browser

Firefox Linux/Mint

### Additional environment information

This occurred on my primary installation (hosted service) and on a local copy (Raspberry Pi 8Gb running Ubuntu Server and Apache2.4)

**Comment by fiwswe** [comment]
Before your [next to last commit](https://github.com/stroggprog/toucher2/commit/e6c3f0b51896ba6b6f03742ec9375ce3babc7097), the [toucher2 Plugin](https://www.dokuwiki.org/plugin:toucher2) had the same base name as as the [Toucher Plugin](https://www.dokuwiki.org/plugin:toucher).

That most likely caused the confusion.

**Comment by stroggprog** [comment]
Aah, many  thanks, I'll try to avoid such confusion in the future
