### ISSUE TITLE
Bug/Feature: Allow ignoring range requests in config

### ISSUE THREAD

**Issue by kosta** [dokuwiki/dokuwiki#4330]
### The problem

I setup a dokuwiki on a domainfactory (popular german web hoster), they basically allow a one-click install. Everything worked out of the box but file _downloads_ failed with http status code 416 "Requested Range Not Satisfiable". This is probably due to a misconfiguration at my web hoster. 

It seems a handful of other people hat similar issues and the fix is to add this line to `.htaccess` so that the bad range header is ignored:

```
RequestHeader unset Range
```

However I had not touched `.htaccess` in ages and needed some setup time first. If there was an option in dokuwiki to ignore Range requests (as a workaround), that would have saved me an hour of my life :) 

Would you accept a pull request that accepts a boolean option to ignore range request headers? I believe it should just boil down to a `|| ignore_range_request_headers` [here](https://github.com/dokuwiki/dokuwiki/blob/0945fedd54766721afd4c07315a3c9fc0f3fb936/inc/httputils.php#L109) plus some tests.

### Version of DokuWiki

Release 2024-02-06b "Kaos"

### PHP Version

8-3-FCGI

**Comment by splitbrain** [comment]
What exact range request do they send? It seems very weird to me that they send a range request at all. The only thing I could imagine is that they send an empty range header. It would still be weird but at least somewhat understandable.

**Comment by kosta** [comment]
> What exact range request do they send?

Sadly, I dont know. Is there a config option to log that easily? That would also make it easier to send them a bug report, which I should do anyway. Otherwise, I can of course edit the source code to write a log line or extend the exception message or something.

**Comment by splitbrain** [comment]
A php file like this should suffice:

```php
<?php
var_dump($_SERVER['HTTP_RANGE']);
```

**Comment by kosta** [comment]
Thanks for the code, I added a file to my server and moved the `.htaccess`out of the way. This gave me:

```
string(15) "bytes=0-5242879" 
```

I dont know what they are doing but that's what they send. I will contact them about it. I am sure my browser did not send a range header.

**Comment by kosta** [comment]
They responded that this is a side effect of their server-side caching and the htaccess workaround is what they recommend. Incredible. If you a agree, I would close the issue because I dont think we should enable that behaviour 🙃
