### ISSUE TITLE
DokuWiki on Caddy always "logged in"

### ISSUE THREAD

**Issue by SamP20** [dokuwiki/dokuwiki#4348]
### The problem

I'm trying to run DokuWiki under Caddy (using the [recommended config](https://www.dokuwiki.org/install:caddy)), but have noticed that the logout button is displayed even when not logged in. I believe this is because Caddy is setting the `REMOTE_USER` environment variable even when it's empty https://github.com/caddyserver/caddy/blob/825fe48e0654dc6e4e065df364a51ea79488e44b/modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go#L307. This is confusing DokuWiki which is just checking if the `$_SERVER["REMOTE_USER"]` variable exists, not whether it's an empty string (see https://github.com/dokuwiki/dokuwiki/blob/d07a9ff3dfb737b03df3af27a513589c0f300c26/inc/Menu/Item/Login.php#L20 for example)

Would it be acceptable to add a workaround to unset the `$_SERVER["REMOTE_USER"]` variable if it's an empty string?

### Version of DokuWiki

2024-02-06b "Kaos"

### PHP Version

8.2

### Webserver and version of webserver

Caddy v2.8.4 h1:q3pe0wpBj1OcHFZ3n/1nl4V4bxBrYoSoab7rL9BMYNk= on Debian

### Additional environment information

I am also using the `authdiscourse` plugin, however I don't believe this is related to the issue. I have compared to a similar installation under Nginx which doesn't have the logout button issue.

### Relevant logs and/or error messages

```text
Note: redacted fields have been replaced with ***. All others are unmodified.

$_SERVER:

Array
(
    [USER] => wiki
    [HOME] => /srv/wiki
    [HTTP_SEC_FETCH_DEST] => document
    [SERVER_PROTOCOL] => HTTP/3.0
    [SERVER_NAME] => ***
    [HTTP_SEC_FETCH_USER] => ?1
    [HTTP_SEC_FETCH_SITE] => none
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:132.0) Gecko/20100101 Firefox/132.0
    [HTTP_SEC_GPC] => 1
    [HTTP_COOKIE] => DokuWiki=***; lightDarkToggle=light
    [HTTPS] => on
    [REMOTE_USER] => 
    [REMOTE_ADDR] => ***
    [HTTP_SEC_FETCH_MODE] => navigate
    [HTTP_DNT] => 1
    [HTTP_X_FORWARDED_PROTO] => https
    [CONTENT_LENGTH] => 0
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [REMOTE_PORT] => 52826
    [GATEWAY_INTERFACE] => CGI/1.1
    [SSL_CIPHER] => TLS_AES_128_GCM_SHA256
    [SCRIPT_FILENAME] => /***/doku.php
    [REQUEST_SCHEME] => https
    [SCRIPT_NAME] => /doku.php
    [REMOTE_HOST] => ***
    [HTTP_ACCEPT_LANGUAGE] => en-GB,en;q=0.5
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
    [PATH_INFO] => 
    [AUTH_TYPE] => 
    [HTTP_PRIORITY] => u=0, i
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br, zstd
    [HTTP_HOST] => ***
    [DOCUMENT_URI] => /doku.php
    [QUERY_STRING] => id=%2Fhome&do=debug
    [REMOTE_IDENT] => 
    [HTTP_X_FORWARDED_HOST] => ***
    [SERVER_PORT] => 443
    [SERVER_SOFTWARE] => Caddy/v2.8.4
    [REQUEST_METHOD] => GET
    [DOCUMENT_ROOT] => ***
    [CONTENT_TYPE] => 
    [HTTP_X_FORWARDED_FOR] => ***
    [SSL_PROTOCOL] => TLSv1.3
    [REQUEST_URI] => /home?do=debug
    [FCGI_ROLE] => RESPONDER
    [PHP_SELF] => /doku.php
    [REQUEST_TIME_FLOAT] => 1731105815.7495
    [REQUEST_TIME] => 1731105815
)
```

**Comment by SamP20** [comment]
I can confirm that adding the following to my `local.protected.php` fixes the issue:

```php
<?php

if(isset($_SERVER['REMOTE_USER']) && $_SERVER['REMOTE_USER'] === '') {
    unset($_SERVER['REMOTE_USER']);
}
```

I'm happy to create a PR to put it somewhere more central if you think it's useful.

**Comment by splitbrain** [comment]
I guess this should be part of `auth_setup()` . PR welcome
