### ISSUE TITLE
[Config] Proxy password field causes Firefox to inappropriately autofill login information

### ISSUE THREAD

**Issue by sirocyl** [dokuwiki/dokuwiki#4362]
### The problem

In the Configuration Manager, Firefox seems to confuse the entire form for an auto-fillable login box, and puts a user's DokuWiki login password under the proxy password field, and the username under the "Notification -> Always send change notifications to this email address" field. This happens out of sight usually, until one clicks the "Save" button, and get informed of invalid configuration information.

<details><summary>A workaround I'm using. Wouldn't recommend for everyone, requires hacking the code.</summary>

A workaround I employed, since I don't use the proxy settings, was to eliminate them. This won't work for everyone, but if someone happens to google up and see this issue, you can probably apply this patch.
```diff
diff --git a/lib/plugins/config/settings/config.metadata.php b/lib/plugins/config/settings/config.metadata.php
index 2935fb7ff..66524c777 100644
--- a/lib/plugins/config/settings/config.metadata.php
+++ b/lib/plugins/config/settings/config.metadata.php
@@ -256,9 +256,9 @@ $meta['hidewarnings'] = ['onoff'];
 $meta['_network'] = ['fieldset'];
 $meta['dnslookups'] = ['onoff'];
 $meta['jquerycdn'] = ['multichoice', '_choices' => [0, 'jquery', 'cdnjs']];
-$meta['proxy____host'] = ['string', '_pattern' => '#^(|[a-z0-9\-\.+]+)$#i'];
-$meta['proxy____port'] = ['numericopt'];
-$meta['proxy____user'] = ['string'];
-$meta['proxy____pass'] = ['password', '_code' => 'base64'];
-$meta['proxy____ssl'] = ['onoff'];
-$meta['proxy____except'] = ['string'];
+//$meta['proxy____host'] = ['string', '_pattern' => '#^(|[a-z0-9\-\.+]+)$#i'];
+//$meta['proxy____port'] = ['numericopt'];
+//$meta['proxy____user'] = ['string'];
+//$meta['proxy____pass'] = ['password', '_code' => 'base64'];
+//$meta['proxy____ssl'] = ['onoff'];
+//$meta['proxy____except'] = ['string'];
```

</details>

### Version of DokuWiki

commit b67cd410 from master

### PHP Version

8.3

### Webserver and version of webserver

Installed through a git clone on the server itself. Debian bookworm, nginx and rewrite configuration present but not enabled in dokuwiki.

### Browser and version of browser, operating system running browser

Firefox 132.0.2 with sync enabled and saved passwords for my dokuwiki instance. No password-management extensions, only the included "Saved Passwords" function.

**Comment by splitbrain** [comment]
Note to self: https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Turning_off_form_autocompletion

**Comment by sirocyl** [comment]
Just saw the above - @splitbrain I'll give your commit a try on my server in a sec (when I get back to a PC) and see if it changes the behavior. \o

**Comment by sirocyl** [comment]
#4364 seems to fix it. \o/ It still _offers_ to enter a password when you click the field; but it doesn't come in prefilled when the page loads, as if it were a login form.

And the *actual* login form is still prefilled, as expected.
