### ISSUE TITLE
On Template Page, lightbox of images not working

### ISSUE THREAD

**Issue by msmick** [dokuwiki/dokuwiki#4371]
### The problem

Thumbnails of templates are listed down the page.. When clicking the first few thumbnails the lightbox feature is not displaying the images, also, in the upper left of the lightbox appears to try to load, or at least is counting up a large number of images. When it finally reaches the top of the count, it never loads though. 

https://www.dokuwiki.org/template

Also during this process it seems to be bugging out and the close button the on the lightbox wasn't working either. 

### Version of DokuWiki

2024 latest on website

### PHP Version

8.3

### Browser and version of browser, operating system running browser

Brave / Chrome based,

**Comment by splitbrain** [comment]
fixed in pluginrepo plugin
