### ISSUE TITLE
[Dokuwiki Website/Forum/Wiki] General Issue

### ISSUE THREAD

**Issue by eightysixed** [dokuwiki/dokuwiki#4379]
It appears that the server that hosts forum.dokuwiki.org doesn't send email. Looks good, I don't think I've seen it since it's been upgraded. Flarum, I assume?

Anyway, I can't get into my account, which is weird because I use 1Password so I know the login is correct. 
I did the "Forgot Your Password" thing, and it never sends an email. I tried three times.

No harm, no foul, I tried to create a new account.
It never sends a new account confirmation email :(

This leads me to two things:
1.) Can I have my original account back, please? :) (account name matches this one - mostly because I want to update/contribute to the Wiki)
2.) More importantly, the email server is misbehaving :)

Thank you!

**Comment by splitbrain** [comment]
Hmm, can you try a password reset again? I changed a bit of the mail config. Also please check your spam folder.

**Comment by eightysixed** [comment]
> Hmm, can you try a password reset again? I changed a bit of the mail config. Also please check your spam folder.

Good morning! Just tried the password reset again. No go. Also tried to resend the confirmation email of the 'new' account, and no confirmation on that still, either. And yes, spam folder has been checked :)

Main email is a GApps for Business account, and the other is Protonmail. Neither are receiving email from forum.dokuwiki.org (my guess is on it not sending email, though :) ).

**Comment by eightysixed** [comment]
It's been two weeks, so I figured I'd give it a try for the nth time, and it finally worked. Closing this.
I'm surprised no one said anything :p
